VOCAB_DOMAINS[0].deck = [
["nostro account","往账账户","我行在他行开立的账户"],
["vostro account","来账账户","他行在我行开立的账户"],
["correspondent banking","代理行业务","跨境汇款的关键通道，反洗钱高风险领域"],
["remittance","汇款"],
["letter of credit (L/C)","信用证"],
["trade finance","贸易融资"],
["syndicated loan","银团贷款"],
["underwriting","承销 / 包销"],
["custody","资产托管"],
["custodian","托管人"],
["derivative","衍生品"],
["interest rate swap (IRS)","利率互换"],
["FX spot / forward / swap","即期 / 远期 / 掉期外汇"],
["settlement","结算、交割"],
["clearing","清算"],
["clearing house","清算所"],
["collateral","担保物、抵押品"],
["haircut","折扣率、估值减值"],
["margin call","追加保证金通知"],
["leverage ratio","杠杆率"],
["capital adequacy","资本充足"],
["Basel III","巴塞尔协议 III"],
["CET1 (Common Equity Tier 1)","核心一级资本"],
["risk-weighted assets (RWA)","风险加权资产"],
["liquidity coverage ratio (LCR)","流动性覆盖率"],
["net stable funding ratio (NSFR)","净稳定资金比率"],
["ICAAP / ILAAP","内部资本 / 流动性充足评估"],
["stress testing","压力测试"],
["balance sheet","资产负债表"],
["provisioning","计提拨备"],
["impairment","减值"],
["non-performing loan (NPL)","不良贷款"],
["exposure","风险敞口"],
["counterparty / counterparty risk","交易对手 / 交易对手风险"],
["fiduciary duty","受托责任"],
["mandate","委托、授权"],
["prospectus","招股说明书"],
["ISDA Master Agreement","国际掉期与衍生工具主协议"],
["SWIFT MT103 / MT202","客户汇款 / 行间头寸调拨报文"],
["IBAN / BIC","国际银行账号 / 银行识别码"],
["CHAPS","英国大额英镑实时清算系统"],
["BACS","英国批量自动清算系统"],
["Faster Payments","英国快速支付系统"],
["SEPA","单一欧元支付区"],
["open banking","开放银行"],
["PSD2","支付服务指令二"],
["e-money institution (EMI)","电子货币机构"],
["onboarding / offboarding","客户准入 / 客户退出"],
["KYC refresh","客户尽调定期更新"],
["de-risking","去风险化（退出高风险客户）"],
["ring-fencing","业务隔离（零售与投行分离）"],
["resolution / bail-in","处置 / 内部纾困"],
["securitisation","证券化"],
["repo (repurchase agreement)","回购"],
["reverse repo","逆回购"],
["netting","净额结算"],
["sub-participation","分参与"],
["facility / drawdown","授信额度 / 提款"],
["covenant","契约条款（贷款合同中的承诺）"],
["payment rail","支付通道"],
["instant payment","即时支付"],
["RTGS (real-time gross settlement)","实时全额清算系统"],
["ISO 20022","国际支付报文标准（MX 报文）"],
["SWIFT gpi","全球支付创新（可追踪跨境汇款）"],
["standing settlement instruction (SSI)","标准结算指令"],
["trade date / value date","交易日 / 起息日"],
["T+2","交易后第二个工作日交收"],
["payment versus payment (PvP)","付款交割同步","外汇结算的经典风险缓释安排"],
["delivery versus payment (DvP)","券款对付"],
["free of payment (FoP)","纯券过户（不带资金交收）"],
["settlement risk","结算风险"],
["Herstatt risk","赫斯塔特风险","跨时区结算导致的一方已付、一方未付风险"],
["novation","债务更替","把一方权利义务整体替换为第三方"],
["assignment","债权转让","与 novation 的区别是原方仍可能保留义务"],
["revolving credit facility (RCF)","循环信贷额度"],
["term loan","定期贷款"],
["bridge loan","过桥贷款"],
["project finance","项目融资"],
["structured finance","结构融资"],
["asset-backed securities (ABS)","资产支持证券"],
["covered bond","担保债券"],
["senior / subordinated debt","优先债 / 次级债"],
["event of default (EOD)","违约事件"],
["financial covenant","财务承诺条款","如杠杆率、利息覆盖倍数"],
["forbearance","宽容处理、暂缓执行"],
["work-out / restructuring","债务重组、不良化解"],
["expected credit loss (ECL)","预期信用损失"],
["IFRS 9","国际财务报告准则第 9 号","决定减值三阶段划分"],
["risk appetite statement (RAS)","风险偏好声明"],
["ALM (asset-liability management)","资产负债管理"],
["net interest income (NII)","净利息收入"],
["cost-income ratio","成本收入比"],
["return on equity (RoE)","净资产收益率"],
["RAROC","风险调整后资本回报率"],
["wholesale funding","批发融资"],
["deposit franchise","存款基础"],
["true sale","真实出售","证券化中资产是否真正出表的关键判断"],
["SPV (special purpose vehicle)","特殊目的载体"],
["banking book / trading book","银行账簿 / 交易账簿"],
["mark-to-market","按市值计价"],
["fair value","公允价值"],
["initial margin / variation margin","初始保证金 / 变动保证金"],
["central counterparty (CCP)","中央对手方"],
["reconciliation","对账"],
["nostro break","往账差异"],
["suspense account","暂记账户","款项归属不明时暂时挂账"],
["dormant account","休眠账户"],
["legal entity identifier (LEI)","法人机构识别编码"],
["cash pooling","现金池","集团资金归集安排"],
["securities lending","证券借贷"],
["sub-custody","次托管"],
["corporate actions","公司行为","分红、配股、股东大会等"],
["margin lending","保证金贷款"],
["structured product","结构性产品"]
];

VOCAB_DOMAINS[1].deck = [
["anti-money laundering (AML)","反洗钱"],
["counter-terrorist financing (CTF)","反恐融资"],
["money laundering (ML)","洗钱"],
["terrorist financing (TF)","恐怖融资"],
["financial crime","金融犯罪","银行内部通常用这个词统称 AML、制裁、欺诈、贿赂"],
["financial crime compliance (FCC)","金融犯罪合规"],
["predicate offence","上游犯罪"],
["placement / layering / integration","处置 / 离析 / 整合（洗钱三阶段）"],
["Know Your Customer (KYC)","客户身份识别"],
["Customer Due Diligence (CDD)","客户尽职调查"],
["Enhanced Due Diligence (EDD)","强化尽职调查"],
["Simplified Due Diligence (SDD)","简化尽职调查"],
["ongoing monitoring","持续监测"],
["Ultimate Beneficial Owner (UBO)","最终受益人"],
["beneficial ownership","受益所有权"],
["Politically Exposed Person (PEP)","政治公众人物"],
["source of funds (SOF)","资金来源","这笔钱从哪来"],
["source of wealth (SOW)","财富来源","这个人的全部身家怎么来的"],
["adverse media","负面舆情筛查"],
["sanctions screening","制裁筛查"],
["suspicious activity report (SAR)","可疑活动报告（AML 语境）"],
["suspicious transaction report (STR)","可疑交易报告"],
["tipping off","泄密（向当事人透露已被上报）","英国法下的刑事犯罪"],
["Defence Against Money Laundering (DAML)","反洗钱抗辩 / 同意申请"],
["Money Laundering Reporting Officer (MLRO)","反洗钱报告官"],
["Nominated Officer","指定报告官"],
["Financial Intelligence Unit (FIU)","金融情报中心"],
["National Crime Agency (NCA)","英国国家犯罪调查局"],
["UKFIU","英国金融情报中心"],
["transaction monitoring (TM)","交易监测"],
["alert / alert triage","警报 / 警报分诊"],
["red flag","危险信号"],
["structuring / smurfing","拆分交易"],
["threshold","阈值"],
["risk-based approach (RBA)","风险为本方法"],
["customer risk rating / risk scoring","客户风险评级 / 风险评分"],
["risk appetite","风险偏好"],
["Money Laundering Regulations 2017","英国反洗钱条例 2017"],
["JMLSG Guidance","英国反洗钱行业指引"],
["6AMLD","第六号欧盟反洗钱指令"],
["record keeping / audit trail","记录保存 / 审计轨迹"],
["escalate / escalation memo","上报 / 上报备忘"],
["correspondent banking due diligence","代理行尽职调查"],
["wire transfer","电汇"],
["unusual activity","异常活动"],
["customer risk assessment (CRA)","客户风险评估"],
["trigger event","触发事件"],
["periodic review","定期复核"],
["remediation","整改"],
["lookback review","回溯审查"],
["typology","（犯罪）类型学"],
["typologies report","类型报告"],
["trade-based money laundering (TBML)","贸易洗钱"],
["invoice manipulation","发票操纵"],
["over- / under-invoicing","高开发票 / 低开发票"],
["phantom shipment","幽灵货运","单证齐全但货根本不存在"],
["carousel fraud","旋转木马骗税"],
["shell company","空壳公司"],
["front company","前台公司"],
["nominee director / shareholder","名义董事 / 名义股东"],
["bearer share","无记名股票"],
["trust and company service provider (TCSP)","信托与公司服务提供商"],
["professional enabler","专业协助者","律师、会计师等为洗钱提供便利的人"],
["gatekeeper","守门人","金融业在反洗钱中的角色定位"],
["cuckoo smurfing","杜鹃式拆分"],
["hawala / hundi","哈瓦拉","非正式跨境汇款体系"],
["underground banking","地下钱庄"],
["money mule / mule account","钱骡 / 钱骡账户"],
["authorised push payment (APP) fraud","授权推送支付欺诈","英国最受关注的支付欺诈类型"],
["romance fraud","情感诈骗"],
["invoice redirection fraud","发票改向欺诈"],
["CEO fraud","冒充高管诈骗"],
["pig butchering","杀猪盘"],
["crypto laundering","加密货币洗钱"],
["mixer / tumbler","混币器"],
["privacy coin","隐私币"],
["chain-hopping","链跳","在不同区块链间转移以躲避追踪"],
["national risk assessment (NRA)","国家风险评估"],
["business-wide risk assessment (BWRA)","全业务风险评估","英国 MLR 2017 的强制要求"],
["geographic risk","地域风险"],
["product / service risk","产品服务风险"],
["delivery channel risk","交付渠道风险"],
["control testing","控制测试"],
["independent testing","独立测试"],
["compliance monitoring","合规监控"],
["quality assurance (QA)","质量保证"],
["first / second / third line","第一 / 第二 / 三道防线"],
["aged alerts","超期未处理警报"],
["key risk indicator (KRI)","关键风险指标"],
["key performance indicator (KPI)","关键绩效指标"],
["management information (MI)","管理信息","给管理层的量化报告"],
["board reporting","董事会报告"],
["policy owner","政策责任人"],
["tone from the top","高层基调"],
["whistleblowing","内部举报"],
["remediation plan","整改计划"],
["past business review (PBR)","历史业务审查"],
["training completion rate","培训完成率"],
["regulatory expectation","监管期望"],
["consent regime","同意制度","SAR 上报后等待 NCA 同意才能继续交易"]
];

VOCAB_DOMAINS[2].deck = [
["sanctions regime","制裁制度"],
["designated person / entity","被列名个人 / 实体"],
["asset freeze","资产冻结"],
["OFAC","美国财政部海外资产控制办公室"],
["SDN List","特别指定国民名单"],
["50% Rule","50% 规则","被制裁方直接或间接持股过半即视为受制裁"],
["OFSI","英国金融制裁执行办公室"],
["EU sanctions","欧盟制裁"],
["secondary sanctions","次级制裁","美国对非美国主体的域外制裁"],
["sectoral sanctions","行业制裁"],
["comprehensive sanctions","全面制裁"],
["circumvention / evasion","规避 / 逃避"],
["screening list","筛查名单"],
["fuzzy matching","模糊匹配"],
["false positive","误报"],
["true match","真实命中"],
["potential match","潜在命中"],
["name / transaction / payment screening","名单 / 交易 / 支付筛查"],
["licence (UK) / license (US)","许可","注意英式拼写 licence 是名词"],
["derogation / exemption","例外许可 / 豁免"],
["blocked transaction","被冻结交易"],
["rejected payment","被拒付的款项"],
["export control","出口管制"],
["dual-use goods","两用物项"],
["military end-user","军事最终用户"],
["end-use","最终用途"],
["ECCN (Export Control Classification Number)","出口管制分类编码"],
["embargo","禁运"],
["freeze and report","冻结并上报"],
["vessel screening","船舶筛查"],
["ownership and control test","所有权与控制判定"],
["humanitarian carve-out","人道主义例外"],
["sanctions compliance programme","制裁合规体系"],
["HM Treasury","英国财政部","英国制裁的发布机关"],
["Sanctions and Anti-Money Laundering Act 2018","2018 年制裁与反洗钱法","英国脱欧后制裁制度的法律基础"],
["consolidated list","综合名单"],
["UK Sanctions List","英国制裁名单"],
["UN Security Council resolution","联合国安理会决议"],
["BIS (Bureau of Industry and Security)","美国工业与安全局"],
["EAR (Export Administration Regulations)","美国出口管理条例"],
["ITAR","美国国际武器贸易条例"],
["Entity List","实体清单","美国商务部限制出口的实体名单"],
["Denied Persons List","拒绝人员清单"],
["Affiliates Rule","关联方规则"],
["sanctions nexus","制裁关联点","判断一笔业务是否触及制裁的连结点"],
["US person","美国人士","美国制裁域外适用的核心概念"],
["facilitation","促成","禁止协助他人规避制裁"],
["economic resources","经济资源"],
["making available","提供（资金或经济资源）","制裁禁令中的核心动词"],
["dominant influence","支配性影响"],
["flag state","船旗国"],
["AIS (Automatic Identification System)","船舶自动识别系统"],
["dark fleet","影子船队","关闭 AIS 以规避制裁的油轮群"],
["ship-to-ship transfer","船对船过驳"],
["price cap","价格上限","G7 对俄油的价格上限机制"],
["attestation (price cap)","价格上限声明"],
["certificate of origin","原产地证明"],
["stop list / watchlist","禁止名单 / 观察名单"],
["rescreening","重新筛查"],
["lookback screening","回溯筛查"],
["screening tuning","筛查规则调优","降低误报率的核心工作"],
["voluntary self-disclosure","自愿披露"],
["civil penalty / criminal penalty","民事处罚 / 刑事处罚"],
["strict liability","严格责任","制裁违规通常不要求证明主观故意"],
["reasonable cause to suspect","有合理理由怀疑"]
];
