/* 新增领域：税务合规与信息交换（tax） */
VOCAB_DOMAINS[18].deck = [
["tax compliance","税务合规"],
["tax evasion vs avoidance","逃税与避税之别","前者刑事、后者合法但有争议，是合规沟通的关键区分"],
["withholding tax","预提所得税"],
["double taxation treaty","避免双重征税协定"],
["permanent establishment","常设机构"],
["transfer pricing","转让定价","关联交易定价，是税基侵蚀的核心议题"],
["arm's length principle","独立交易原则"],
["base erosion and profit shifting (BEPS)","税基侵蚀与利润转移"],
["Pillar Two / global minimum tax","第二支柱 / 全球最低税","15% 全球最低有效税率"],
["qualified domestic minimum top-up tax","合格国内最低补足税"],
["country-by-country reporting","国别报告"],
["controlled foreign company (CFC) rules","受控外国公司规则"],
["general anti-abuse rule (GAAR)","一般反滥用规则"],
["purpose test","目的测试"],
["disclosure of tax avoidance schemes (DOTAS)","避税方案披露制度","英国推行的强制披露机制"],
["promoter of tax avoidance scheme","避税方案推广人"],
["FATCA","美国海外账户税收合规法","Foreign Account Tax Compliance Act"],
["CRS","共同申报准则","OECD 主导的金融账户涉税信息自动交换"],
["common reporting standard","共同申报准则（全称）"],
["automatic exchange of information (AEOI)","涉税信息自动交换"],
["tax residency","税务居民身份"],
["tax identification number (TIN)","纳税人识别号"],
["reportable account","须申报账户"],
["controlling person","控制人","CRS 下穿透至实际控制人"],
["self-certification","自我证明","开户时客户填写的税务身份声明"],
["tax due diligence","税务尽职调查"],
["VAT","增值税","英国标准税率为 20%"],
["reverse charge","反向征收"],
["input / output tax","进项 / 销项税"],
["tax ruling","税务裁定"],
["tax authority enquiry","税务机关调查"],
["HMRC","英国税务海关总署","HM Revenue & Customs"],
["penalty regime","处罚制度"],
["voluntary disclosure of tax","自愿补税披露"],
["criminal evasion","刑事逃税"],
["sanctions and tax nexus","制裁与税务的交叉"],

["know your customer's tax position","了解客户的税务状况"],

["tax risk framework","税务风险框架"],
["uncertain tax position","不确定税务事项"],
["deferred tax","递延税"],
["effective tax rate","有效税率"],
["tax provision","税务准备 / 计提"],
["acceptable tax planning","可接受的税务筹划"]
];

/* 新增领域：网络安全与运营韧性（cyber） */
VOCAB_DOMAINS[19].deck = [
["operational resilience","运营韧性","英国监管的核心要求：在中断中仍能交付重要业务服务"],
["important business service (IBS)","重要业务服务"],
["impact tolerance","影响容忍度","IBS 中断可承受的最长时间"],
["business continuity plan (BCP)","业务连续性计划"],
["disaster recovery (DR)","灾难恢复"],
["recovery time objective (RTO)","恢复时间目标"],
["recovery point objective (RPO)","恢复点目标"],
["cyber resilience","网络韧性"],
["cyber risk","网络风险"],
["threat landscape","威胁态势"],
["threat actor","威胁行为者"],
["advanced persistent threat (APT)","高级持续性威胁"],
["ransomware","勒索软件"],
["malware / trojan / worm","恶意软件 / 木马 / 蠕虫"],
["distributed denial of service (DDoS)","分布式拒绝服务攻击"],
["social engineering","社会工程学攻击"],
["phishing / spear phishing","钓鱼 / 鱼叉式钓鱼"],
["business email compromise (BEC)","商务邮件欺诈"],
["zero-day vulnerability","零日漏洞"],
["patch management","补丁管理"],
["vulnerability assessment","漏洞评估"],
["penetration testing","渗透测试"],
["red team exercise","红队演练"],
["threat intelligence","威胁情报"],
["indicators of compromise (IoC)","失陷指标"],
["security operations centre (SOC)","安全运营中心"],
["SIEM","安全信息与事件管理系统"],
["endpoint detection and response (EDR)","端点检测与响应"],
["multi-factor authentication (MFA)","多因素认证"],
["least privilege","最小权限"],
["privileged access management (PAM)","特权访问管理"],
["identity and access management (IAM)","身份与访问管理"],
["network segmentation","网络隔离"],
["encryption at rest / in transit","静态 / 传输中加密"],
["key management","密钥管理"],
["data loss prevention (DLP)","数据防泄露"],
["security incident","安全事件"],
["incident response plan","事件响应预案"],
["major incident","重大事件"],
["escalation matrix","上报矩阵"],
["regulatory notification","监管通报","重大网络事件须在法定时限内上报"],
["material cyber incident","重大网络事件"],
["post-incident review","事后复盘"],
["lessons identified","教训识别"],
["threat hunting","威胁狩猎"],
["attack surface","攻击面"],
["supply chain attack","供应链攻击"],
["DORA","欧盟数字运营韧性法案","对金融实体的 ICT 风险管理提出统一要求"],
["ICT third-party risk","信息通信技术第三方风险"],
["critical ICT provider","关键 ICT 服务提供商"],
["cloud concentration risk","云集中度风险"],
["data residency","数据驻留"],
["post-quantum cryptography","后量子密码学"],
["security awareness training","安全意识培训"],
["simulated phishing campaign","模拟钓鱼演练"]
];
