/* 新增领域：英国生活事务（civi） */
VOCAB_DOMAINS[20].deck = [
["National Insurance number","国民保险号","俗称 NI number，工作与纳税必备，通常缩写为 NINO"],
["National Insurance contributions","国民保险费","工资单上的 NICs，用于累积养老金权利"],
["PAYE","预扣所得税制","Pay As You Earn，多数雇员自动适用"],
["tax code","税号代码","如 1257L，决定免税额度，出错会导致少发工资"],
["P60","年度纳税证明","财年结束后由雇主提供"],
["P45","离职纳税汇总表","换工作时交给新雇主"],
["self-assessment tax return","自评申报表","副业或高收入者须自行申报"],
["council tax","市政税","按住房分级征收，单人居住可申请 25% 折扣"],
["council tax band","市政税等级","A 至 H 共八级，取决于房产估值"],
["single person discount","单人居住折扣"],
["energy supplier","电力燃气供应商"],
["standing charge","固定日租费","即便不用气电也照收"],
["meter reading","抄表读数"],
["water rates","水费"],
["TV licence","电视牌照费","看直播或 BBC iPlayer 就必须买"],
["tenancy agreement","租赁合同"],
["assured shorthold tenancy (AST)","保障性短期租赁","英国最常见的私人租房形式"],
["landlord / letting agent","房东 / 租赁中介"],
["deposit protection scheme","押金保护计划","法律强制，押金须在 30 日内存入"],
["tenancy deposit","租赁押金"],
["inventory check","房屋清单核验","入住与退租时逐项对照，退押金的关键证据"],
["check-in / check-out report","入住 / 退租报告"],
["notice period","通知期"],
["break clause","中途解约条款"],
["guarantor","担保人","无英国信用记录时常被要求提供"],
["rent in advance","预付租金"],
["holding deposit","定金","法定上限为一周租金"],
["right to rent check","租赁资格核查","房东必须核验租客的合法居留身份"],
["flat share / house share","合租"],
["bills included","含账单","合租房广告常见表述，务必确认含哪些"],
["studio flat","单间公寓"],
["one-bed flat","一居室"],
["leasehold / freehold","租赁产权 / 永久产权","英国房产的两大产权类型，差异极大"],
["ground rent","地租"],
["service charge","物业管理费"],
["mortgage offer","按揭批准函"],
["stamp duty land tax","印花税"],
["conveyancing","房产过户法律事务"],
["EPC","能源性能证书","Energy Performance Certificate，租房买房必备"],
["GP registration","注册全科医生","落地后应尽早办理，没注册看病很麻烦"],
["GP surgery","社区诊所"],
["NHS number","国民健康服务编号"],
["NHS 111","非紧急医疗咨询热线"],
["A&E","急诊科","Accident & Emergency"],
["walk-in centre","免预约诊疗中心"],
["pharmacy / chemist","药房"],
["prescription charge","处方费","英格兰地区收费，苏格兰与威尔士已取消"],
["referral","转诊"],
["waiting list","候诊名单"],
["private health insurance","私人医疗保险"],
["current account","活期账户"],
["savings account","储蓄账户"],
["proof of address","地址证明","开户与办事的高频材料"],
["credit history / credit file","信用记录","刚到英国时几乎为零，会影响租房与开户"],
["overdraft","透支额度"],
["direct debit","直接借记","授权商户按需扣款，账单常用"],
["standing order","定期转账指令","固定金额固定日期，你自己设定"],
["contactless payment","非接触式支付","英国普及度极高，单笔通常上限 100 英镑"],
["cashpoint / ATM","自动取款机","英国口语里 cashpoint 比 ATM 更常见"],
["mobile banking app","手机银行"],
["challenger bank","新兴数字银行","Monzo、Starling、Revolut 等"],
["Individual Savings Account (ISA)","个人储蓄账户","利息与资本利得免税，每年有额度上限"],
["Premium Bonds","溢价债券","英国国家储蓄局的抽奖型储蓄产品"],
["driving licence","驾照"],
["DVLA","英国车辆管理局","Driver and Vehicle Licensing Agency"],
["MOT test","车辆年检"],
["road tax","车辆税"],
["congestion charge","伦敦拥堵费"],
["ULEZ","超低排放区","Ultra Low Emission Zone，不达标车辆须缴费"],
["council","地方议会","负责垃圾清运、市政税、图书馆等"],
["recycling collection","垃圾回收"],
["999 / 111 / 101","紧急 / 医疗咨询 / 非紧急警务电话"]
];

/* 新增领域：英国文化与社交（soc） */
VOCAB_DOMAINS[21].deck = [
["small talk","寒暄闲聊","英国职场与社交的润滑剂，不是浪费时间"],
["weather talk","聊天气","英国社交的默认开场，本质是表达善意"],
["How's it going?","最近怎么样？","回答不用真诚汇报，一句 Not too bad 即可"],
["You alright?","你好啊？","英式招呼语，**不是**真的在问你身体好不好"],
["Not too bad.","还行。","英式回答的最高级克制表达"],
["Can't complain.","没什么可抱怨的。"],
["Cheers.","谢谢 / 干杯","英国用法极广，从道谢到告别都能用"],
["Ta.","谢啦","非常口语的道谢，英式特色"],
["Fancy a cuppa?","要不要来杯茶？","cuppa = cup of tea，办公室社交的万能开场"],
["Do you want a brew?","要来杯茶吗？","brew 在英式口语中也指一杯茶"],
["tea round","茶水轮值","办公室文化里人人都要轮到，别只让别人给你倒"],
["drinks round","轮流请酒","酒吧文化铁律：轮到你就得请，不能只喝别人的"],
["pub quiz","酒吧知识竞赛"],
["pub lunch","酒吧午餐"],
["after-work drinks","下班小酌"],
["Sunday roast","周日烤肉","英国家庭聚餐的经典形式"],
["full English breakfast","全套英式早餐"],
["bank holiday","法定假日","每年只有八天，全英统一"],
["Boxing Day","节礼日","12 月 26 日"],
["Bonfire Night","篝火之夜","11 月 5 日，纪念火药阴谋"],
["Remembrance Day","阵亡将士纪念日","11 月 11 日前后佩戴罂粟花"],
["Pancake Day","煎饼日","忏悔星期二，全民吃薄饼"],
["Christmas do","公司圣诞聚会","do 在英国口语中泛指活动、聚会"],
["Christmas jumper day","圣诞毛衣日"],
["dress code","着装规范"],
["smart casual","商务休闲","比 business casual 更得体一档，别穿运动鞋"],
["business attire","正装"],
["hot-desking","流动性工位"],
["breakout area","休息区"],
["water cooler moment","茶水间的非正式交流"],
["personal space","个人空间","英国人比南欧人更在意身体距离"],
["understatement","低调陈述","「Not bad」往往是「相当好」，这是英式表达的核心特征"],
["self-deprecation","自嘲"],
["British reserve","英式克制","不轻易表露强烈情绪"],
["banter","玩笑打趣","英式幽默的主要形式，但要分清边界避免越界"],
["taking the mickey","取笑调侃","熟悉同事间的常用语，正式场合绝不可用"],
["irony","反讽","英国幽默的底层语法，字面意思常与真实意思相反"],
["queuing etiquette","排队礼仪","插队是英国社会最严重的失礼之一"],
["sorry culture","道歉文化","英国人平均一天说 sorry 八次，多数并非认错"],
["excuse me vs sorry","打扰一下 / 抱歉","进出门与人擦身而过时用 sorry 更地道"],
["Sorted.","搞定了。"],
["Brilliant.","太好了。"],
["Lovely.","很好。"],
["Fair enough.","有道理 / 可以。"],
["I'm easy.","我都行。"],
["Bear with me.","稍等一下。"],
["to pop round","顺道过去一趟"],
["to swing by","顺便过来"],
["to grab a bite","随便吃点"],
["to be knackered","累趴了"],
["to be gutted","特别失望"],
["to be chuffed","特别高兴"],
["to be gobsmacked","目瞪口呆"],
["a bit of a faff","有点麻烦事"],
["not my cup of tea","不是我的菜"],
["Premier League","英超联赛"],
["Six Nations","六国橄榄球赛"],
["Wimbledon","温布尔登网球赛"],
["broadsheet / tabloid","大报 / 小报"],
["Financial Times","金融时报","英国金融圈的必读报纸"],
["Radio 4","BBC 第四广播台","英国中产与专业人士的信息主流渠道"],
["BBC Sounds","BBC 音频平台"]
];

/* 补强：英国日常生活：食品与日用品 / 伦敦地标与交通 */
VOCAB_DOMAINS[12].deck = VOCAB_DOMAINS[12].deck.concat([
["supermarket chains","英国主要超市","高端 Waitrose/M&S，主流 Tesco/Sainsbury's，平价 Asda/Morrisons，折扣 Aldi/Lidl"],
["meal deal","套餐组合","三明治加零食加饮料的固定价套餐，英国午餐文化核心"],
["crisps","薯片","英国叫 crisps，chips 是薯条，最常见的点餐误解"],
["chips","薯条","不是薯片"],
["fizzy drink","碳酸饮料","英国不用 soda 这个词"],
["squash","浓缩果汁饮料"],
["biscuit","饼干","英式 biscuit 近似美式 cookie，但更硬更脆"],
["scone","司康饼","读 /skɒn/ 或 /skəʊn/ 都行，加奶油还是果酱先放是永恒争论"],
["clotted cream","凝脂奶油","英式下午茶的灵魂"],
["jam","果酱"],
["banger","香肠","口语说法，配 mash 即香肠土豆泥"],
["bap / barm / cob","小圆面包","地区叫法不同，是判别口音地域的经典测试"],
["black pudding","黑布丁","血肠，全套英式早餐的组成部分"],
["bacon rasher","培根片"],
["beans on toast","烤豆吐司"],
["fish and chips","炸鱼薯条"],
["takeaway","外卖","英式用 takeaway，美式用 takeout"],
["off-licence","酒类专卖店"],
["newsagent","报刊便利店"],
["chemist","药房 / 日化店","Boots 是最常见的连锁"],
["queue","排队","英国排队的严格程度超乎想象"],
["till / checkout","收银台"],
["self-checkout","自助收银"],
["loyalty card","积分卡","Tesco Clubcard 与 Nectar 最普及"],
["Nectar points","Nectar 积分"],
["Best before vs Use by","最佳食用期与保质期","前者是品质提示，后者过期不得食用"],
["food hygiene rating","食品卫生评级"],
["deposit return scheme","瓶罐押金退还计划","苏格兰已实施，英格兰即将推行"],
["brolly","雨伞","英国口语缩写，十有八九会用到"],
["wellies","雨靴"],
["plaster","创可贴","英式用 plaster，美式用 Band-Aid"],
["paracetamol","扑热息痛","英国最常见的止痛药，超市限量购买"],
["ibuprofen","布洛芬"],
["loo / toilet / bog","厕所的三种说法","公开场合用 toilet 或 loo，bog 极口语"],
["tap","水龙头","英式用 tap，美式用 faucet"],
["bin","垃圾桶","英式用 bin，美式用 trash can"],
["hoover","吸尘器 / 吸尘","品牌名泛化为动词，英国特有用法"],
["washing-up liquid","洗洁精"],
["ironing board","熨衣板"],
["duvet","羽绒被","英国寝具的默认形式，不是 blanket"],
["kettle","电水壶","英国家庭使用频率最高的电器之一"]
]);

VOCAB_DOMAINS[13].deck = VOCAB_DOMAINS[13].deck.concat([
["the City of London","伦敦金融城","square mile，与 Westminster 的行政伦敦是两回事"],
["Canary Wharf","金丝雀码头","另一大金融中心，多家投行总部所在"],
["Bank","银行站","伦敦地铁站名，金融城的交通枢纽"],
["Moorgate","摩尔盖特","金融城北部车站"],
["Liverpool Street","利物浦街站"],
["Liverpool Street station","利物浦街火车站","通往 Stansted 机场与东英格兰"],
["Old Street","老街站","科技城 Silicon Roundabout 所在"],
["Barbican","巴比肯","金融城北侧的住宅与文化中心"],
["St Paul's","圣保罗座堂"],
["the Monument","伦敦大火纪念碑"],
["Tower Bridge","塔桥","常被误认作 London Bridge，两者完全不同"],
["London Bridge","伦敦桥"],
["Tower of London","伦敦塔"],
["the Shard","碎片大厦","西欧最高建筑"],
["Tate Modern","泰特现代美术馆"],
["Borough Market","博罗市场"],
["South Bank","南岸"],
["Waterloo","滑铁卢站","南岸主要交通枢纽"],
["Paddington","帕丁顿站","通往希思罗机场快线与西英格兰"],
["King's Cross / St Pancras","国王十字 / 圣潘克拉斯站","欧洲之星出发站"],
["Euston","尤斯顿站","通往曼彻斯特、格拉斯哥等北方城市"],
["Marylebone","马里波恩站"],
["Victoria","维多利亚站"],
["Earl's Court","伯爵宫站"],
["Canary Wharf station","金丝雀码头站","Jubilee line 与 DLR 交汇"],
["Westminster","威斯敏斯特站"],
["Whitehall","白厅街","英国政府各部委所在地"],
["Downing Street","唐宁街"],
["Houses of Parliament","议会大厦"],
["Buckingham Palace","白金汉宫"],
["the Mall","林荫路"],
["Trafalgar Square","特拉法加广场"],
["Piccadilly Circus","皮卡迪利圆环"],
["Covent Garden","考文特花园"],
["Camden Town","卡姆登镇"],
["Notting Hill","诺丁山"],
["Brick Lane","砖巷"],
["Greenwich","格林尼治"],
["O2 Arena","O2 体育馆"],
["Wembley","温布利"],
["Heathrow / Gatwick / Stansted / Luton / City","五大伦敦机场","City 机场离金融城最近，但只能起降小型机"],
["Elizabeth line","伊丽莎白线","横贯伦敦的东西向快速铁路，2022 年全线通车"],
["Thameslink","泰晤士连线"],
["Overground","伦敦地上铁"],
["TfL","伦敦交通局","Transport for London"],
["Oyster card","牡蛎卡","实体交通卡，现多被非接触银行卡取代"],
["contactless cap","非接触支付每日/每周封顶","用银行卡直接刷闸机比买票更划算"],
["Travelcard","交通通票"],
["peak / off-peak","高峰 / 非高峰","票价差异显著，通勤成本的关键变量"],
["zone 1-6","一至六区","伦敦交通分区计费体系"],
["Railcard","铁路优惠卡","如 26-30 Railcard，可省三分之一"],
["National Rail","英国国家铁路"],
["advance single","预售单程票","通常比现场购票便宜一半以上"],
["split ticketing","分段购票","英国合法且常见的省钱技巧"],
["delay repay","延误补偿","火车晚点超过一定时长可申请退款"],
["strike action","罢工","英国铁路罢工频繁，需提前查 National Rail 网站"],
["bus pass / Hopper fare","公交票 / 换乘优惠","一小时内换乘公交不额外收费"],
["congestion charge zone","拥堵费区域"],
["Santander Cycles","伦敦共享单车"],
["Black cab","黑色出租车","须通过「知识」考试，可路边招手"],
["licensed minicab","预约制出租车","不能路边招手，必须提前预约"]
]);
