VOCAB_DOMAINS[3].deck = [
["GDPR / UK GDPR","欧盟通用数据保护条例 / 英国版"],
["Data Protection Act 2018","英国 2018 年数据保护法"],
["Information Commissioner's Office (ICO)","英国信息专员办公室"],
["personal data","个人数据"],
["special category data","特殊类别数据（敏感数据）"],
["data subject","数据主体"],
["data controller / processor","数据控制者 / 处理者"],
["joint controller","共同控制者"],
["lawful basis","合法性基础","六种之一：同意、合同、法定义务、重大利益、公共任务、正当利益"],
["consent","同意"],
["legitimate interests","正当利益"],
["data minimisation","数据最小化"],
["purpose limitation","目的限制"],
["storage limitation","存储限制"],
["Data Protection Impact Assessment (DPIA)","数据保护影响评估"],
["Data Protection Officer (DPO)","数据保护官"],
["subject access request (SAR)","数据主体访问请求","注意与 AML 的 Suspicious Activity Report 同缩写"],
["right to erasure / to rectification","删除权 / 更正权"],
["data breach","数据泄露"],
["72-hour notification","72 小时通报义务"],
["cross-border transfer","跨境传输"],
["adequacy decision","充分性认定"],
["Standard Contractual Clauses (SCCs)","标准合同条款"],
["Binding Corporate Rules (BCRs)","约束性公司规则"],
["Schrems II","Schrems II 判决","推翻隐私盾，重塑跨大西洋数据传输"],
["Records of Processing Activities (ROPA)","处理活动记录"],
["privacy notice","隐私声明"],
["pseudonymisation / anonymisation","假名化 / 匿名化"],
["retention period","保存期限"],
["accountability principle","问责原则","GDPR 的核心原则：你必须能证明自己合规"],
["data protection by design and by default","设计阶段与默认的数据保护"],
["transparency","透明性"],
["right to restriction of processing","限制处理权"],
["right to object","反对权"],
["right to data portability","数据可携权"],
["data processing agreement (DPA)","数据处理协议"],
["sub-processor","次级处理者"],
["controller-processor agreement","控制者—处理者协议"],
["international data transfer agreement (IDTA)","国际数据传输协议","英国版 SCC"],
["UK Addendum","英国附录","附加在欧盟 SCC 上以适用英国法"],
["transfer risk assessment (TRA)","传输风险评估"],
["EU-US Data Privacy Framework","欧美数据隐私框架"],
["data sharing agreement","数据共享协议"],
["law enforcement request","执法机关请求"],
["confidentiality / availability / integrity breach","保密性 / 可用性 / 完整性泄露","GDPR 对泄露的三种分类"],
["Freedom of Information Act (FOIA)","信息自由法"],
["PECR (e-privacy)","英国电子隐私法规","管 Cookie 和直接营销"],
["cookie consent","Cookie 同意"],
["soft opt-in","柔性选择加入","既有客户营销的例外规则"],
["direct marketing consent","直接营销同意"],
["employee monitoring","员工监控"],
["redaction","遮蔽处理","回复 SAR 时删除第三方信息"],
["automated decision-making","自动化决策"],
["profiling","画像分析"],
["records retention schedule","记录保存时间表"],
["legal hold","法律保留","诉讼或调查期间禁止删除"],
["e-discovery","电子取证"],
["data loss prevention (DLP)","数据防泄漏"],
["data governance","数据治理"],
["data lineage","数据血缘","数据从哪来到哪去的追溯链"],
["data quality","数据质量"],
["AI Act","欧盟人工智能法案"]
];

VOCAB_DOMAINS[4].deck = [
["Financial Conduct Authority (FCA)","英国金融行为监管局"],
["Prudential Regulation Authority (PRA)","英国审慎监管局"],
["Bank of England (BoE)","英格兰银行"],
["Financial Policy Committee (FPC)","金融政策委员会"],
["Senior Managers and Certification Regime (SM&CR)","高级管理人员与认证制度"],
["approved person","受认可人士（SM&CR 之前制度）"],
["PRIN (Principles for Businesses)","FCA 商业原则"],
["SYSC","FCA 高级管理与系统控制手册"],
["COBS","FCA 商业行为手册"],
["CASS","FCA 客户资产手册"],
["MAR (Market Abuse Regulation)","市场滥用条例"],
["SUP","FCA 监管手册"],
["threshold conditions","准入门槛条件"],
["Part 4A permission","第四 A 部分许可"],
["appointed representative","指定代表"],
["Consumer Duty","消费者责任（2023 生效）"],
["vulnerable customer","弱势客户"],
["Treating Customers Fairly (TCF)","公平对待客户"],
["MiFID II / MiFIR","金融工具市场指令二 / 条例"],
["EMIR / UK EMIR","欧洲市场基础设施条例"],
["transaction reporting","交易报告"],
["best execution","最佳执行"],
["appropriateness / suitability","适当性 / 适合性"],
["inducements","诱导性安排"],
["product governance / target market","产品治理 / 目标市场"],
["inside information","内幕信息"],
["insider dealing","内幕交易"],
["market manipulation","市场操纵"],
["unlawful disclosure","非法披露"],
["suspicious transaction and order report (STOR)","可疑交易与指令报告"],
["wall-crossing","越墙程序","把内幕信息告知交易人员并留痕的流程"],
["conflicts of interest / Chinese wall","利益冲突 / 信息隔离墙"],
["Final Notice / prohibition order","最终处罚通知 / 禁业令"],
["financial penalty","罚款"],
["VREQ (voluntary requirement)","自愿要求"],
["s166 skilled person review","第 166 条专家审查"],
["attestation","签署确认"],
["Securities and Exchange Commission (SEC)","美国证券交易委员会"],
["FINRA","美国金融业监管局"],
["CFTC","美国商品期货交易委员会"],
["Dodd-Frank Act","多德-弗兰克法案"],
["Volcker Rule","沃尔克规则"],
["Bank Secrecy Act (BSA)","美国银行保密法"],
["FinCEN","美国金融犯罪执法网络"],
["CTR (Currency Transaction Report)","现金交易报告"],
["USA PATRIOT Act","美国爱国者法案"],
["Foreign Corrupt Practices Act (FCPA)","美国反海外腐败法"],
["UK Bribery Act 2010","英国 2010 年反贿赂法"],
["Matter Requiring Attention (MRA)","需关注事项"],
["consent order","同意令"],
["examination","监管检查"],
["Financial Services and Markets Act 2023","2023 年金融服务与市场法","脱欧后英国监管框架的基石"],
["FSMA 2000","2000 年金融服务与市场法"],
["Consumer Credit Act 1974","1974 年消费信贷法"],
["MCOB","FCA 抵押贷款业务规则"],
["BCOBS","FCA 银行业务行为规则"],
["ICOBS","FCA 保险业务行为规则"],
["DISP","FCA 投诉处理规则"],
["client money","客户资金"],
["statutory trust","法定信托","CASS 下客户资金的持有法律基础"],
["internal reconciliation requirement","内部对账要求"],
["Financial Ombudsman Service (FOS)","金融申诉专员服务"],
["Financial Services Compensation Scheme (FSCS)","金融服务补偿计划"],
["complaint handling rules","投诉处理规则"],
["eight-week deadline","八周期限","投诉处理的法定期限"],
["final response letter","最终答复函"],
["redress","赔偿、救济"],
["Payment Systems Regulator (PSR)","支付系统监管局"],
["APP fraud reimbursement","APP 欺诈赔付"],
["confirmation of payee","收款人姓名核对","英国防转账诈骗的核心机制"],
["strong customer authentication (SCA)","强客户认证"],
["3-D Secure","3D 安全验证"],
["safeguarding","资金保障","支付机构隔离客户资金的义务"],
["variation of permission","许可变更"],
["senior manager function (SMF)","高级管理职能"],
["prescribed responsibilities","规定职责"],
["fit and proper","适当人选"],
["regulatory reference","监管证明","SM&CR 下必须出具的从业背景证明"],
["certification regime","认证制度"],
["conduct rules","行为规则"],
["notifiable matter","需通报事项"],
["Securities Act 1933 / Exchange Act 1934","美国证券法 / 证券交易法"],
["Investment Advisers Act 1940","美国投资顾问法"],
["OCC / Federal Reserve / FDIC","美国货币监理署 / 美联储 / 联邦存款保险公司"],
["NYDFS","纽约州金融服务局"],
["Rule 10b-5","美国交易法 10b-5 规则","反证券欺诈的核心条款"],
["Sarbanes-Oxley Act","萨班斯-奥克斯利法"],
["Regulation Best Interest (Reg BI)","最大利益规则"],
["Regulation S-P","美国客户信息隐私规则"],
["Corporate Transparency Act","美国企业透明度法"],
["beneficial ownership information (BOI) reporting","受益所有权信息报告"],
["Wells notice","韦尔斯通知","SEC 拟起诉前的告知程序"],
["cease and desist order","停止令"]
];

VOCAB_DOMAINS[5].deck = [
["Could you bear with me for a moment?","请稍等一下","电话或会上最常用的缓冲句"],
["Let's take this offline.","我们私下再聊","会上不想展开时的标准说法"],
["I'll revert to you.","我回头答复你","英式商务高频，不是「恢复」的意思"],
["Let me loop you in.","我把你加进沟通里"],
["Just a heads-up.","先跟你说一声"],
["Shall we get started?","我们可以开始了吗"],
["Can everyone hear me?","大家能听到我说话吗"],
["You're on mute.","你静音了"],
["Let me share my screen.","我共享一下屏幕"],
["Could you say that again?","你能再说一遍吗"],
["Sorry, I didn't quite catch that.","抱歉我没太听清"],
["Let me rephrase that.","我换个说法"],
["To build on what [name] said…","接着 [某人] 刚才说的"],
["I'd like to push back on that.","这一点我有不同意见"],
["With respect, I see it differently.","恕我直言，我的看法不同"],
["I wonder if we could look at it another way.","我们是不是可以换个角度看"],
["That's a fair point, but…","这点有道理，不过……"],
["Let's park that for now.","这个先放一放"],
["Who's taking the minutes?","谁来做会议纪要"],
["Let's take that as an action.","这条我们记为待办"],
["I'll follow up by [date].","我会在 [日期] 前跟进"],
["Any questions before we move on?","继续之前有疑问吗"],
["To summarise where we are…","总结一下目前的进展"],
["For the avoidance of doubt…","为避免歧义","合规文书最高频的限定语之一"],
["On a without-prejudice basis","在不影响权利的前提下"],
["We're required to…","我们有义务……"],
["This falls within scope of…","这属于……的范围"],
["I'd rather not commit to that at this stage.","这个阶段我不想先给出承诺"],
["Let me take that away and come back to you.","我回去确认后再答复你"],
["For your records","供你存档"],
["Please note for completeness","为完整起见，请注意"],
["I'm easy / I'm not fussed.","我都行、我不介意"],
["Not too bad, can't complain.","还行，没什么可抱怨的","英式寒暄标准回答"],
["That's not ideal.","这不太理想","英式委婉表达不满"],
["This is a bit of a grey area.","这属于灰色地带"],
["We need to get our ducks in a row.","我们得先把内部理顺"],
["Let's not reinvent the wheel.","别重复造轮子了"],
["Ballpark figure","大致数字"],
["Deep dive","深入分析"],
["Touch base","简短沟通一下"],
["Bandwidth","精力 / 可用时间"],
["Move the needle","产生实质影响"],
["Circle back","回头再谈"],
["I'd like to flag a concern.","我想提出一个关切"],
["Just to be clear on the scope…","先把范围界定清楚"],
["That falls outside my remit.","这不在我的职责范围内"],
["I'll own that action.","这条我来负责"],
["Do we have a decision owner?","谁负责拍板"],
["What's the ask here?","具体是要什么"],
["Let's align on next steps.","我们对齐一下后续步骤"],
["I'll bring this to the committee.","我提交到委员会"],
["Should we escalate this?","要不要升级处理"],
["That's a fair challenge.","这个质疑有道理"],
["Let me play devil's advocate.","我来唱个反调"],
["I'd caveat that.","我加个限定条件"],
["I'm not comfortable signing off on this.","我不便批准这件事"],
["subject to legal review","待法律审查"],
["subject to board approval","待董事会批准"],
["conditional on","以……为条件"],
["off the record","非正式地（不作记录）"],
["Chatham House Rule","查塔姆研究所规则","发言可引用但不得指明来源"],
["in the interests of transparency","为透明起见"],
["to be prudent","为审慎起见"],
["we're mindful of","我们注意到"],
["we'd rather err on the side of caution","我们宁可谨慎一点"],
["it would be remiss of us not to","我们若不做便有失职之嫌"],
["we're obliged to","我们有义务"],
["this is a matter of judgement","这属于判断问题"],
["reasonable and proportionate","合理且相称","监管看控制措施是否符合这一标准"],
["documenting the rationale","记录决策理由"],
["in a timely manner","及时地"],
["with immediate effect","立即生效"],
["please treat as urgent","请按紧急事项处理"],
["as you're aware","如你所知"],
["further to our conversation","承接我们的谈话"],
["I'm writing to follow up on","我致函跟进"],
["I'd be grateful if you could","若你能……我将不胜感激"],
["Please do not hesitate to contact me","请随时联系我"]
];
