VOCAB_DOMAINS[6].deck = [
["board of directors","董事会"],
["non-executive director (NED)","非执行董事"],
["chair / chairperson","董事长"],
["CEO / CFO / COO / CRO","首席执行官 / 财务 / 运营 / 首席风险官"],
["Chief Compliance Officer (CCO)","首席合规官"],
["general counsel (GC)","总法律顾问"],
["company secretary","公司秘书","英国公司治理中的法定角色"],
["audit committee","审计委员会"],
["risk committee","风险委员会"],
["remuneration committee","薪酬委员会"],
["nomination committee","提名委员会"],
["executive committee (ExCo)","执行委员会"],
["management committee (ManCo)","管理委员会"],
["ALCO (asset-liability committee)","资产负债管理委员会"],
["new product committee (NPC)","新产品委员会"],
["reputational risk committee","声誉风险委员会"],
["steering committee","指导委员会"],
["working group","工作组"],
["terms of reference (ToR)","职责范围、工作大纲"],
["front office","前台（业务部门）"],
["middle office","中台（风控、产品控制）"],
["back office","后台（运营、结算）"],
["relationship manager (RM)","客户关系经理"],
["coverage / coverage banker","客户覆盖岗"],
["product specialist","产品专家"],
["treasury","资金部"],
["risk function","风险部门"],
["credit risk","信用风险"],
["market risk","市场风险"],
["operational risk","操作风险"],
["conduct risk","行为风险"],
["reputational risk","声誉风险"],
["financial crime risk","金融犯罪风险"],
["compliance advisory","合规咨询（业务条线的对口合规）"],
["internal audit","内部审计"],
["in-house counsel / legal counsel","内部法律顾问"],
["external counsel","外部律师"],
["head of compliance","合规负责人"],
["group / entity / branch / subsidiary","集团 / 法人 / 分行 / 子公司"],
["line of business (LoB)","业务条线"],
["desk","交易台 / 业务组"],
["reporting line","汇报线"],
["dotted line","虚线汇报"],
["span of control","管理幅度"],
["secondment","借调"],
["probation period","试用期"],
["appraisal / performance review","绩效评估"],
["objective / KPI","目标 / 关键绩效指标"],
["stakeholder","利益相关方"],
["counterpart department","对口部门"],
["three lines of defence","三道防线","业务、风控合规、内审"],
["escalation matrix","升级矩阵","决定什么事项报给谁"],
["committee paper","委员会审议文件"],
["minutes / matters arising","会议纪要 / 待跟进事项"],
["action log","待办清单"],
["sign-off / approval authority","签批 / 审批权限"],
["delegated authority","授权额度"]
];

VOCAB_DOMAINS[7].deck = [
["supervisory review and evaluation process (SREP)","监管审查与评估程序"],
["supervisory college","监管联席会"],
["risk assessment framework","风险评估框架"],
["supervisory plan","监管计划"],
["information request (s165)","信息请求（第 165 条）"],
["skilled person review (s166)","专家审查（第 166 条）"],
["on-site inspection","现场检查"],
["off-site review","非现场审查"],
["desk-based review","桌面审查"],
["scoping meeting","范围界定会议"],
["opening meeting","开场会议"],
["closing meeting","总结会议"],
["management letter","管理层函"],
["findings","检查发现事项"],
["observation","观察事项"],
["recommendation","建议"],
["action plan","行动计划"],
["remediation timeline","整改时间表"],
["root cause analysis","根因分析"],
["control gap","控制缺陷"],
["control effectiveness","控制有效性"],
["design effectiveness","设计有效性"],
["operating effectiveness","运行有效性"],
["walkthrough test","穿行测试"],
["substantive testing","实质性测试"],
["sample selection","样本选取"],
["working paper","工作底稿"],
["fieldwork","现场工作阶段"],
["follow-up review","后续审查"],
["overdue action","逾期整改"],
["interview notes","访谈记录"],
["internal investigation","内部调查"],
["forensic review","法务会计审查"],
["document preservation","文件保全"],
["legal privilege","法律职业特权","内部调查文件能否豁免披露的关键"],
["privileged report","受特权保护的报告"],
["Upjohn warning","Upjohn 警示","访谈员工前必须告知其陈述可能归公司所有"],
["disciplinary process","纪律程序"],
["gross misconduct","严重不当行为"],
["regulatory referral","移交监管处理"],
["notifiable breach","需通报的违规事项"],
["lessons learned","经验教训"],
["attestation letter","确认函"],
["self-assessment questionnaire","自查问卷"],
["voluntary undertaking","自愿承诺"],
["thematic review","主题审查"],
["mystery shopping","神秘顾客检查"],
["complaint file review","投诉档案审查"],
["consumer harm","消费者损害"],
["fair value assessment","公允价值评估（Consumer Duty 要求）"]
];

VOCAB_DOMAINS[8].deck = [
["herein / hereof / hereto / hereunder","本文件中 / 本文件的 / 附于本文件 / 依本文件"],
["hereinafter","以下称"],
["therein / thereof / thereto","其中 / 其 / 向其"],
["whereas","鉴于"],
["recitals","引言部分（鉴于条款）"],
["in witness whereof","以资证明","签署条款的固定起首语"],
["operative provisions","正文条款"],
["representation","陈述","对事实的说明"],
["warranty","保证","对事实的承诺，违者可索赔"],
["indemnity","补偿"],
["hold harmless","使免受损害"],
["limitation of liability","责任限制"],
["force majeure","不可抗力"],
["material adverse change (MAC)","重大不利变化"],
["termination for cause / for convenience","违约解除 / 任意解除"],
["notice period","通知期"],
["governing law","适用法律"],
["jurisdiction clause","管辖条款"],
["arbitration","仲裁"],
["mediation","调解"],
["expert determination","专家裁定"],
["severability","可分割性"],
["entire agreement clause","完整协议条款"],
["no waiver","不弃权条款"],
["set-off","抵销"],
["conditions precedent (CP)","先决条件"],
["conditions subsequent","后决条件"],
["best / reasonable endeavours","最大努力 / 合理努力","英国法下两者法律强度不同"],
["time is of the essence","时间为关键要素"],
["subject to contract","以正式合同为准"],
["pari passu","同等顺位"],
["pro rata","按比例"],
["bona fide","善意"],
["inter alia","除其他外"],
["mutatis mutandis","作必要修改后适用"],
["ultra vires","越权"],
["de facto / de jure","事实上的 / 法律上的"],
["prima facie","初步看来"],
["ex parte","单方（对方不在场）"],
["standard of proof","证明标准"],
["balance of probabilities","概然性权衡","英式民事标准"],
["beyond reasonable doubt","排除合理怀疑","刑事标准"],
["burden of proof","举证责任"],
["disclosure / discovery","证据开示"],
["without admission of liability","不承认责任"],
["release","免责文件"],
["settlement agreement","和解协议"],
["liquidated damages","预定损害赔偿"],
["specific performance","强制履行"],
["injunctive relief","禁令救济"],
["undertaking","承诺、保证"],
["escrow","第三方托管"],
["due execution","适当签署"],
["counterpart","副本"],
["deed vs agreement","契据 / 协议","英国法下 deed 无需对价即可执行"],
["without prejudice","不损害权利"],
["non-disclosure agreement (NDA)","保密协议"],
["estoppel","禁反言"],
["piercing the corporate veil","刺破公司面纱"],
["joint and several liability","连带责任"]
];
