VOCAB_DOMAINS[9].deck = [
["income statement / P&L","利润表 / 损益表"],
["statement of financial position","财务状况表（资产负债表）"],
["cash flow statement","现金流量表"],
["statement of changes in equity","所有者权益变动表"],
["notes to the financial statements","财务报表附注"],
["revenue / turnover","收入 / 营业额","英国英语更常用 turnover"],
["cost of sales","销售成本"],
["gross profit","毛利"],
["operating expenses (opex)","营业费用"],
["EBITDA","息税折旧摊销前利润"],
["EBIT","息税前利润"],
["net profit / bottom line","净利润"],
["accrual","应计项目"],
["deferred income","递延收入"],
["prepayment","预付费用"],
["provision","准备金"],
["contingent liability","或有负债"],
["contingent asset","或有资产"],
["work in progress (WIP)","在建项目 / 在制品"],
["inventory","存货"],
["receivables / payables","应收账款 / 应付账款"],
["days sales outstanding (DSO)","应收账款周转天数"],
["working capital","营运资金"],
["goodwill","商誉"],
["intangible assets","无形资产"],
["amortisation","摊销"],
["depreciation","折旧"],
["impairment testing","减值测试"],
["recoverable amount","可收回金额"],
["carrying amount","账面价值"],
["fair value hierarchy","公允价值层级"],
["off-balance sheet","表外项目"],
["related party transaction","关联方交易"],
["consolidation","合并报表"],
["audit opinion / qualified opinion","审计意见 / 保留意见"],
["going concern","持续经营"],
["materiality","重要性水平"],
["internal control over financial reporting (ICFR)","财务报告内部控制"],
["intercompany","公司间往来"],
["segment reporting","分部报告"],
["IFRS / UK GAAP / US GAAP","国际财务报告准则 / 英国准则 / 美国准则"],
["accounting policy","会计政策"],
["restatement","（报表）重述"],
["prior period adjustment","前期调整"],
["cut-off","截止（期间划分）"],
["substance over form","实质重于形式"],
["prudence","审慎性"]
];

VOCAB_DOMAINS[10].deck = [
["import / export","进口 / 出口"],
["bill of lading","提单","物权凭证，贸易融资的核心单据"],
["air waybill","空运单"],
["commercial invoice","商业发票"],
["packing list","装箱单"],
["inspection certificate","检验证明"],
["documentary collection","跟单托收"],
["documents against payment (D/P)","付款交单"],
["documents against acceptance (D/A)","承兑交单"],
["open account","赊销"],
["advance payment","预付款"],
["sight / usance letter of credit","即期 / 远期信用证"],
["issuing bank","开证行"],
["advising bank","通知行"],
["confirming bank","保兑行"],
["negotiating bank","议付行"],
["discrepancy","不符点"],
["waiver of discrepancies","不符点豁免"],
["UCP 600","跟单信用证统一惯例"],
["standby letter of credit (SBLC)","备用信用证"],
["bank guarantee","银行保函"],
["performance bond","履约保函"],
["advance payment guarantee","预付款保函"],
["forfaiting","福费廷","无追索买断远期票据"],
["factoring","保理"],
["receivables finance","应收账款融资"],
["supply chain finance","供应链融资"],
["reverse factoring","反向保理"],
["pre-shipment finance","装运前融资"],
["post-shipment finance","装运后融资"],
["warehouse receipt","仓单"],
["commodity finance","大宗商品融资"],
["borrowing base","借款基数"],
["tenor","期限"],
["rollover","展期"],
["red flag indicators","红旗指标"],
["multiple invoicing","重复开票"],
["short / over shipping","短装 / 超装"],
["free trade zone","自由贸易区"],
["transit country","中转国"],
["customs declaration","报关单"],
["HS code","海关商品编码"],
["end-user certificate","最终用户证明"]
];

VOCAB_DOMAINS[11].deck = [
["cryptoasset","加密资产"],
["virtual asset service provider (VASP)","虚拟资产服务提供商"],
["cryptoasset business","加密资产业务"],
["custody wallet","托管钱包"],
["hosted / unhosted wallet","托管 / 非托管钱包"],
["private key","私钥"],
["cold / hot wallet","冷钱包 / 热钱包"],
["crypto exchange","加密资产交易所"],
["stablecoin","稳定币"],
["central bank digital currency (CBDC)","央行数字货币"],
["digital pound","数字英镑"],
["tokenisation","代币化"],
["security token","证券型代币"],
["utility token","功能型代币"],
["NFT","非同质化代币"],
["smart contract","智能合约"],
["distributed ledger technology (DLT)","分布式账本技术"],
["blockchain analytics","区块链分析"],
["travel rule","旅行规则","转账须附带发起方与接收方信息"],
["FATF Recommendation 16","FATF 第 16 项建议","旅行规则的出处"],
["on-chain / off-chain","链上 / 链下"],
["DeFi","去中心化金融"],
["staking","质押"],
["mining","挖矿"],
["wallet screening","钱包筛查"],
["attribution","地址归属分析"],
["sanctioned wallet address","受制裁钱包地址"],
["financial promotions regime","金融推广制度","英国对加密广告的准入要求"],
["cryptoasset registration","加密资产注册"],
["MiCA","欧盟加密资产市场条例"],
["open finance","开放金融"],
["API","应用程序接口"],
["screen scraping","屏幕抓取"],
["buy now pay later (BNPL)","先买后付"],
["robo-adviser","智能投顾"],
["neobank / challenger bank","新型银行 / 挑战者银行"],
["payment initiation service provider (PISP)","支付发起服务商"],
["account information service provider (AISP)","账户信息服务商"],
["regtech / suptech","监管科技 / 监管端科技"],
["model risk management","模型风险管理"],
["explainability","可解释性","AI 模型能否解释决策依据"],
["algorithmic trading","算法交易"],
["high-frequency trading (HFT)","高频交易"],
["digital identity","数字身份"],
["eKYC / liveness check","电子 KYC / 活体检测"],
["synthetic identity","合成身份","用真实与虚构信息拼接出的假身份"]
];

VOCAB_DOMAINS[12].deck = [
["chips vs crisps","炸薯条 vs 袋装薯片","英美差异高频踩坑点"],
["aubergine / courgette","茄子 / 西葫芦"],
["rocket / coriander","芝麻菜 / 香菜"],
["spring onion / leek","小葱 / 大葱"],
["semi-skimmed / whole milk","半脱脂 / 全脂牛奶"],
["double cream / single cream","浓奶油 / 淡奶油"],
["clotted cream","凝脂奶油","英式下午茶配司康必备"],
["caster sugar / icing sugar","细砂糖 / 糖粉"],
["porridge","燕麦粥"],
["jacket potato","带皮烤土豆"],
["baked beans","茄汁焗豆"],
["sausage roll / pasty","香肠卷 / 康沃尔肉馅饼"],
["full English / fry-up","英式全套早餐"],
["Sunday roast","周日烤肉大餐"],
["shepherd's pie / cottage pie","牧羊人派（羊肉）/ 农家派（牛肉）"],
["bap / bun / cob / roll","面包卷（各地叫法不同）"],
["biscuit / cookie","饼干","英式 biscuit 指甜饼干，cookie 多指美式软曲奇"],
["scone","司康"],
["meal deal","套餐优惠（主食 + 零食 + 饮料）"],
["takeaway","外卖","英式，不是 takeout"],
["pub / gastropub","酒吧 / 餐吧"],
["checkout / till","收银台"],
["self-checkout","自助结账"],
["trolley / basket","购物车 / 购物篮"],
["receipt","小票"],
["loyalty card (Clubcard / Nectar)","超市会员卡"],
["off-licence","酒类专卖店"],
["corner shop","街角小店"],
["chemist / pharmacy","药房","英国不说 drugstore"],
["prescription","处方"],
["paracetamol","扑热息痛","英国最常用的非处方药"],
["plaster","创可贴","英式，不是 band-aid"],
["GP surgery","社区全科诊所"],
["A&E (Accident & Emergency)","急诊"],
["NHS","英国国家医疗服务体系"],
["flat","公寓","英式，不是 apartment"],
["ground floor / first floor","一楼 / 二楼","英国 ground floor 才是我们说的一楼"],
["lift","电梯","英式，不是 elevator"],
["bin / rubbish","垃圾桶 / 垃圾","英式，不是 trash"],
["washing-up liquid","洗洁精"],
["cling film","保鲜膜","英式，不是 saran wrap"],
["kitchen roll","厨房纸巾"],
["hoover (v.)","用吸尘器打扫"],
["kettle / hob / oven / grill","电水壶 / 灶台 / 烤箱 / 烤架"],
["cutlery","餐具（刀叉勺）"],
["cuppa / brew","一杯茶"],
["queue","排队"],
["queue-jumping","插队","英国人最不能忍的行为之一"],
["tap","水龙头","英式，不是 faucet"],
["wardrobe","衣柜"],
["tumble dryer","滚筒烘干机"],
["letting agent / landlord","房屋中介 / 房东"],
["deposit / tenancy agreement","押金 / 租约"],
["council tax","市政税"],
["utility bills","水电燃气账单"],
["national insurance number","国民保险号"],
["council / borough","地方政府 / 行政区"],
["bank holiday","公共假日"],
["postcode","邮编"]
];

VOCAB_DOMAINS[13].deck = [
["Elizabeth Tower / Big Ben","伊丽莎白塔 / 大本钟","大本钟是钟，塔叫伊丽莎白塔"],
["Palace of Westminster","威斯敏斯特宫（议会大厦）"],
["Westminster Abbey","威斯敏斯特教堂"],
["Buckingham Palace","白金汉宫"],
["Trafalgar Square / Nelson's Column","特拉法加广场 / 纳尔逊纪念柱"],
["Tower of London / Tower Bridge","伦敦塔 / 塔桥"],
["London Bridge","伦敦桥","不是明信片上那座塔桥，别混"],
["St Paul's Cathedral","圣保罗大教堂"],
["The City / Square Mile","伦敦金融城 / 一平方英里"],
["Bank of England / Royal Exchange","英格兰银行 / 皇家交易所"],
["Mansion House / Guildhall","市长官邸 / 市政厅"],
["Canary Wharf","金丝雀码头","第二大金融中心"],
["One Canada Square","加拿大广场一号"],
["The Shard / The Gherkin","碎片大厦 / 小黄瓜"],
["The Cheesegrater / The Walkie-Talkie","奶酪刨大楼 / 对讲机大楼"],
["The Monument","伦敦大火纪念碑"],
["British Museum / National Gallery","大英博物馆 / 国家美术馆"],
["Tate Modern / Tate Britain","泰特现代 / 泰特不列颠"],
["London Eye / South Bank","伦敦眼 / 南岸"],
["Covent Garden / Leicester Square","考文特花园 / 莱斯特广场"],
["Piccadilly Circus / Oxford Street","皮卡迪利圆环 / 牛津街"],
["Regent Street / Bond Street","摄政街 / 邦德街"],
["Soho / Shoreditch / Camden","苏荷 / 肖尔迪奇 / 卡姆登"],
["Notting Hill / Portobello Road","诺丁山 / 波多贝罗路"],
["Borough Market","博罗市场"],
["Hyde Park / Regent's Park","海德公园 / 摄政公园"],
["St James's Park / Green Park","圣詹姆斯公园 / 绿园"],
["Greenwich / Royal Observatory","格林尼治 / 皇家天文台"],
["Kew Gardens / Hampstead Heath","邱园 / 汉普斯特德荒野"],
["King's Cross / St Pancras","国王十字 / 圣潘克拉斯（欧洲之星）"],
["Paddington / Heathrow Express","帕丁顿 / 希思罗快线"],
["The Tube / Underground","伦敦地铁"],
["Overground / DLR / Elizabeth line","地上铁 / 码头区轻轨 / 伊丽莎白线"],
["TfL / Oyster / contactless","伦敦交通局 / 牡蛎卡 / 非接触支付"],
["Zone 1 / terminus","一区 / 终点站"],
["Mind the gap","小心站台空隙"],
["platform / escalator","站台 / 自动扶梯"],
["stand on the right","靠右站立","扶梯左侧留给赶时间的人"],
["black cab / minicab","黑色出租车 / 预约制网约车"],
["Santander Cycles","伦敦共享单车"],
["National Rail / railcard","国家铁路 / 铁路折扣卡"],
["coach station","长途汽车站"],
["Moorgate / Liverpool Street / Bank","金融城三个主要地铁站"],
["Broadgate / Aldgate","金融城办公区与站点"],
["Whitehall","白厅（英国政府街）"],
["Downing Street","唐宁街"],
["Horse Guards Parade","皇家骑兵卫队阅兵场"],
["The Mall","林荫路（通往白金汉宫）"],
["Marble Arch","大理石拱门"],
["Barbican Centre","巴比肯艺术中心"],
["Royal Albert Hall","皇家阿尔伯特音乐厅"],
["Abbey Road","艾比路（披头士斑马线）"],
["Baker Street","贝克街（福尔摩斯 221B）"],
["Regent's Canal","摄政运河"],
["Camden Lock","卡姆登水闸"],
["Little Venice","小威尼斯"],
["Primrose Hill","樱草山"],
["The O2","O2 体育馆"],
["Wembley Stadium","温布利球场"],
["Lord's / The Oval","伦敦两大板球场"],
["Richmond / Wimbledon","里士满 / 温布尔登"],
["Clapham / Brixton / Peckham","克拉珀姆 / 布里克斯顿 / 佩卡姆"],
["peak / off-peak","高峰 / 非高峰（票价时段）"],
["tap in / tap out","刷卡进站 / 出站"]
];
