/* 深化：银行业与国际金融市场 / AML-KYC / 制裁与出口管制 */
VOCAB_DOMAINS[0].deck = VOCAB_DOMAINS[0].deck.concat([
["payment system","支付系统"],
["RTGS","实时全额结算系统","Real-Time Gross Settlement，英国 CHAPS 即属此类"],
["CHAPS","英国大额英镑清算系统","Clearing House Automated Payment System，同日到账"],
["Faster Payments","英国快速支付系统","小额英镑实时到账，7×24 小时"],
["Bacs","英国批量自动清算系统","Bacs Credit / Bacs Direct Debit，通常 3 个工作日"],
["SEPA","单一欧元支付区","Single Euro Payments Area"],
["Fedwire","美联储资金转账系统"],
["TARGET2","欧洲央行实时清算系统"],
["ACH","自动清算所","Automated Clearing House，美国批量支付网络"],
["ISO 20022","国际金融报文标准","结构化报文的全球统一格式，取代传统 SWIFT MT"],
["pacs.008","客户贷记转账报文","ISO 20022 中最核心的支付报文"],
["camt.053","账户对账单报文"],
["SWIFT MT103","客户汇款报文","传统跨境汇款主报文"],
["UETR","唯一端到端交易参考号","Unique End-to-End Transaction Reference，gpi 追踪用"],
["SWIFT gpi","全球支付创新","Global Payments Innovation，提供汇款全程追踪"],
["correspondent bank","代理行"],
["intermediary bank","中间行","转汇链条中的中转机构"],
["beneficiary bank","收款人银行"],
["IBAN","国际银行账号"],
["BIC / SWIFT code","银行识别码"],
["sort code","英国银行分行代码","六位数字，如 20-00-00"],
["national clearing code","国家清算代码","各国本地清算行号的统称"],
["payer / payee","付款人 / 收款人","重音均在第二音节；英式 payee 与 payer 重音一致"],
["payment instruction","支付指令"],
["remittance information","汇款附言","反洗钱筛查的重点字段，需留意结构化拆分"],
["straight-through processing (STP)","直通式处理","无需人工干预的自动处理"],
["repair queue","待修复队列","报文要素不全被挂起的处理流水线"],
["recall / cancellation","召回 / 撤销","支付的追溯处理机制"],
["money market","货币市场"],
["SONIA","英镑隔夜指数平均利率","Sterling Overnight Index Average，英国无风险利率基准"],
["SOFR","有担保隔夜融资利率","Secured Overnight Financing Rate，美元基准"],
["€STR","欧元短期利率"],
["RFR","无风险利率","Risk-Free Rate，LIBOR 退场后的替代基准"],
["term rate","期限利率","由隔夜利率推导出的前瞻性期限基准"],
["compounded rate","复利利率","隔夜利率回溯复利计算法"],
["basis point (bp)","基点","万分之一，100bp = 1%"],
["yield curve","收益率曲线"],
["liquidity coverage ratio (LCR)","流动性覆盖率","优质流动性资产 / 30 天净流出"],
["net stable funding ratio (NSFR)","净稳定资金比率","一年期结构性流动性指标"],
["HQLA","优质流动性资产","High-Quality Liquid Assets"],
["liquidity buffer","流动性缓冲"],
["deposit runoff","存款流失","压力测试中的核心假设之一"],
["deposit insurance","存款保险","英国 FSCS 保障上限为每人每机构 85,000 英镑"],
["CET1 ratio","核心一级资本充足率","Common Equity Tier 1"],
["Tier 1 / Tier 2 capital","一级 / 二级资本"],
["risk-weighted assets (RWA)","风险加权资产"],
["leverage ratio","杠杆率","不依赖风险权重的资本底线指标"],
["MREL","最低自有资金与合格负债要求","欧盟/英国版 TLAC"],
["TLAC","总损失吸收能力","Total Loss-Absorbing Capacity"],
["Basel III","巴塞尔协议 III"],
["Pillar 1 / 2 / 3","第一 / 二 / 三支柱","最低资本要求 / 监管审查 / 市场约束"],
["ICAAP","内部资本充足评估程序","银行自评估资本充足性的年度作业"],
["ILAAP","内部流动性充足评估程序"],
["stress testing","压力测试"],
["capital planning buffer","资本规划缓冲"],
["recovery plan","恢复计划","危机自救方案"],
["resolution plan","处置计划","有序倒闭方案"],
["living will","生前遗嘱","处置计划的通俗说法"],
["repo / reverse repo","回购 / 逆回购","回购是融资，逆回购是融出资金"],
["securities lending","证券借贷"],
["prime brokerage","主经纪商业务"],
["securitisation","证券化"],
["special purpose vehicle (SPV)","特殊目的实体"],
["netting","净额结算"],
["set-off","抵销"],
["close-out netting","终止净额结算","ISDA 主协议的核心机制"],
["novation","合同更替","以新合同取代旧合同，主体变更"],
["assignment","债权让与"],
["sub-participation","从属参与","不改变与原债务人的法律关系"],
["wholesale banking","批发银行"],
["retail banking","零售银行"],
["private banking","私人银行"],
["wealth management","财富管理"],
["corporate banking","对公业务"],
["treasury","资金部 / 司库"],
["ALM","资产负债管理","Asset-Liability Management"],
["nostro reconciliation","往账对账"]
]);

VOCAB_DOMAINS[1].deck = VOCAB_DOMAINS[1].deck.concat([
["placement","放置阶段","洗钱三阶段之首：将现金投入金融体系"],
["layering","离析阶段","通过多层交易切断资金与来源的联系"],
["integration","整合阶段","资金回流合法经济体系"],
["structuring / smurfing","拆分交易","刻意压低于申报门槛，简称 structured deposits"],
["cuckoo smurfing","杜鹃式拆分","利用不知情第三方账户过账的洗钱手法"],
["mule account / money mule","钱骡账户 / 钱骡","以佣金诱使他人出借账户"],
["round-tripping","循环回流","资金出境后再以投资名义回流"],
["loan-back scheme","贷款回流式洗钱"],
["hawala / hundi","哈瓦拉 / 非正规汇款","无实物流转的信任型地下汇款"],
["phantom shipment","幽灵货运","贸易洗钱中虚构不存在的货物"],
["carousel fraud","旋转木马欺诈","循环开具增值税发票骗取退税"],
["APP fraud","授权推送支付欺诈","Authorised Push Payment，受害者自愿转账"],
["authorised push payment scam","授权推送支付骗局"],
["phishing / smishing / vishing","钓鱼 / 短信钓鱼 / 电话钓鱼"],
["romance fraud","杀猪盘 / 恋爱诈骗"],
["investment fraud","投资诈骗"],
["boiler room fraud","锅炉房诈骗","高压电话推销不存在的股票"],
["pump and dump","拉高出货"],
["unauthorised access fraud","未授权侵入欺诈"],
["internal fraud","内部欺诈"],
["third-party fraud","第三方欺诈"],
["first-party fraud","一方欺诈","客户本人虚构事实骗贷"],
["synthetic identity","合成身份","拼接真实与虚构信息制造的身份"],
["account takeover","账户劫持"],
["suspicious activity report (SAR)","可疑活动报告","英国向 NCA 提交；同缩写也指数据主体访问请求"],
["SAR online","英国线上 SAR 提交系统"],
["NCA","英国国家犯罪调查局","National Crime Agency"],
["DAML request","洗钱抗辩许可申请","Defence Against Money Laundering，向 NCA 申请同意后方可交易"],
["consent / refusal","同意 / 拒绝","NCA 对 DAML 申请的两种回复"],
["moratorium period","冻结期","NCA 未决期间的 7 个工作日交易暂停"],
["tipping off","泄露风声","告知嫌疑人其已被举报，本身即刑事犯罪"],
["predicate offence","上游犯罪"],
["criminal property","犯罪财产"],
["proceeds of crime","犯罪所得"],
["terrorist financing","恐怖融资"],
["proliferation financing","扩散融资","为大规模杀伤性武器扩散提供资金"],
["TF risk assessment","恐怖融资风险评估"],
["risk-based approach (RBA)","风险为本方法","FATF 推荐的核心监管原则"],
["business-wide risk assessment (BWRA)","全机构风险评估"],
["customer risk assessment (CRA)","客户风险评估"],
["risk rating","风险评级"],
["risk appetite","风险偏好","反洗钱中用于界定可接受客户与业务"],
["simplified due diligence (SDD)","简化尽职调查"],
["enhanced due diligence (EDD)","强化尽职调查"],
["trigger event","触发事件","如交易异常、负面新闻、客户信息变更"],
["source of funds (SOF)","资金来源","钱从哪里来"],
["source of wealth (SOW)","财富来源","整体财富如何积累"],
["adverse media / negative news","负面新闻筛查"],
["PEP register","政治公众人物名册"],
["relationship manager (RM)","客户关系经理"],
["KYC refresh / remediation","KYC 复检 / 存量整改"],
["periodic review","定期复检"],
["trigger-based review","事件驱动复检"],
["onboarding","开户准入"],
["offboarding / exit","销户 / 关系退出"],
["de-risking","去风险化","整类退出某客户群，监管机构普遍不鼓励"],
["financial inclusion","普惠金融","与去风险化相对的监管关切"],
["transaction monitoring scenario","交易监测场景"],
["threshold-based rule","阈值型规则"],
["typology coverage","类型学覆盖度"],
["alert-to-case conversion rate","警报转案件率","衡量监测系统效率的核心指标"],
["false positive rate","误报率"],
["tuning / optimisation","调优 / 优化"],
["lookback review","回溯审查"],
["sample testing","抽样测试"],
["quality assurance (QA)","质量保证"],
["investigative report","调查报告"]
]);

VOCAB_DOMAINS[2].deck = VOCAB_DOMAINS[2].deck.concat([
["designated person / entity","被列名个人 / 实体"],
["SDN List","特别指定国民名单","美国 OFAC 的核心制裁名单"],
["consolidated list","综合名单","英国 OFSI 维护的金融制裁名单"],
["OFSI","英国金融制裁执行办公室","Office of Financial Sanctions Implementation"],
["asset freeze","资产冻结","制裁中最高频的即时义务"],
["funds and economic resources","资金与经济资源","冻结令的法定标的表述"],
["travel ban","旅行禁令"],
["arms embargo","武器禁运"],
["sectoral sanctions","行业性制裁","针对特定行业而非全面禁运"],
["secondary sanctions","次级制裁","对非美国主体与受制裁方的交易施加惩罚"],
["extraterritorial reach","域外效力"],
["50 per cent rule","50% 规则","受制裁主体合计持股达 50% 的实体视为受制裁"],
["ownership and control test","所有权与控制权测试","英国法下控制权可低于 50%"],
["circumvention","规避"],
["sanctions evasion","制裁规避","主观故意的违规行为"],
["general licence","一般许可","无需逐一申请、满足条件即可适用的豁免"],
["specific licence","特定许可","个案申请"],
["derogation","例外减免"],
["delisting / de-listing request","除名申请"],
["false positive","误报命中"],
["true match","真实命中"],
["potential match / partial match","潜在命中"],
["fuzzy matching","模糊匹配","允许拼写差异的筛查算法"],
["name screening","名单筛查"],
["payment screening","支付筛查","在报文流转环节实时拦截"],
["transaction screening","交易筛查"],
["threshold / sensitivity","阈值 / 灵敏度","调高降误报、调低防漏报的权衡"],
["alert disposition","警报处置结论"],
["whitelist / suppression list","白名单 / 抑制名单","须有独立复核机制，否则是监管雷区"],
["rescreening","重新筛查"],
["screening tool coverage","筛查工具覆盖率"],
["fleet screening","全量批次筛查"],
["ownership screening","股权穿透筛查"],
["vessel screening","船舶筛查"],
["shadow fleet","影子船队","通过换旗、关 AIS 规避价格上限与制裁"],
["AIS","船舶自动识别系统","Automatic Identification System，常被关闭以隐藏轨迹"],
["flag state","船旗国"],
["dark fleet activity","暗船队活动"],
["G7 price cap","七国集团价格上限","针对俄罗斯原油与成品油"],
["attestation","合规声明","供应链中下游主体出具的用途与价格承诺"],
["end-use statement","最终用途声明"],
["dual-use goods","两用物项","民用与军用皆可"],
["catch-all control","兜底管制","物项本身未被列名但用途可疑即可管制"],
["export control classification number (ECCN)","出口管制分类编号"],
["technology transfer","技术转移"],
["deemed export","视同出口","向境内外国人披露技术即视为出口"],
["embargoed jurisdiction","受禁运法域"],
["sanctions nexus","制裁关联点","判断案件是否落入管辖的关键问题"],
["ownership chain","股权链条"],
["control via other means","其他方式控制","如任命多数董事、主导经营"],
["sanctions compliance programme","制裁合规体系"],
["sanctions risk assessment","制裁风险评估"],
["voluntary self-disclosure","主动披露","可显著减轻处罚的关键动作"],
["monetary penalty","罚款"],
["strict liability","严格责任","英国制裁违规无需证明主观故意"]
]);
