/* 深化：英美监管与市场行为 / 数据与隐私保护 / 合规职场与会议口语 */
VOCAB_DOMAINS[4].deck = VOCAB_DOMAINS[4].deck.concat([
["FSMA 2000","英国金融服务与市场法"],
["FSMA 2023","英国金融服务与市场法 2023","确立消费者责任、SMCR 扩展与关键第三方制度"],
["RAO","受监管活动令","Regulated Activities Order，界定哪些活动需牌照"],
["regulated activity","受监管活动","无牌照进行即刑事犯罪"],
["permission","业务许可"],
["variation of permission (VOP)","变更许可"],
["threshold conditions","准入门槛条件"],
["Part 4A permission","第四 A 部分许可","英国存款机构与投资公司的许可依据"],
["PRIN","商业原则","FCA 的 12 条 Principles for Businesses"],
["COBS","商业行为规则","Conduct of Business Sourcebook"],
["SYSC","高级管理层制度与内控","Senior Management Arrangements, Systems and Controls"],
["MCOB","按揭商业行为规则"],
["ICOBS","保险商业行为规则"],
["BCOBS","银行商业行为规则"],
["CONC","消费信贷规则"],
["CASS","客户资产规则","Client Assets Sourcebook，客户钱与自营钱必须隔离"],
["client money","客户资金"],
["statutory trust","法定信托","CASS 项下客户资金的法律性质"],
["DISP","争议解决规则","包含 FOS 与 FSCS 的管辖"],
["FOS","金融申诉专员服务","免费、对消费者有利的独立裁判机构"],
["FSCS","金融服务补偿计划","每人每机构上限 85,000 英镑"],
["approved person","核准人员","受审批准入的个人"],
["senior manager","高级经理"],
["certification employee","认证雇员"],
["SMF / prescribed responsibility","高级管理职能 / 法定职责"],
["conduct rules","行为准则","个体问责制的核心，分五条基本准则"],
["fit and proper","适格与正当"],
["replacement of SMF","高级经理变更"],
["appointed representative","指定代表","依托持牌机构展业的轻牌照安排"],
["host / home state","东道国 / 母国"],
["passporting","通行证制度","英国脱欧后对欧盟已失效，现为 TPR 制度"],
["temporary permissions regime (TPR)","临时许可制度"],
["overseas fund","海外基金"],
["supervisory review and evaluation process (SREP)","监管审查与评估程序"],
["skilled person","专家顾问","FCA 依 FSMA 第 166 条指派的独立审查人"],
["supervisory notice","监管通知"],
["warning notice / decision notice / final notice","警告通知 / 决定通知 / 最终通知"],
["own initiative requirement (OIREQ)","监管主动施加的要求"],
["voluntary requirement","自愿承诺要求"],
["prohibition order","禁业令"],
["financial penalty","金融处罚"],
["redress scheme","赔偿计划"],
["review of past business","历史业务复查"],
["consumer duty","消费者责任","2023 年生效，要求为零售客户交付良好结果"],
["four consumer outcomes","四项消费者结果"],
["consumer understanding","消费者理解"],
["price and value","价格与价值"],
["consumer support","消费者支持"],
["products and services outcome","产品与服务结果"],
["foreseeable harm","可预见损害"],
["vulnerable customer","弱势客户"],
["fair value assessment","公允价值评估"],
["market abuse regulation (MAR)","市场滥用条例"],
["insider dealing","内幕交易"],
["unlawful disclosure","非法披露内幕信息"],
["market manipulation","市场操纵"],
["suspicious transaction and order report (STOR)","可疑交易与指令报告","英国版市场滥用举报"],
["insider list","内幕信息知情人名单"],
["inside information","内幕信息"],
["closed period","静默期"],
["PDMR","履行管理职责人员","Persons Discharging Managerial Responsibilities"],
["disclosure guidance and transparency rules (DTR)","披露指引与透明度规则"],
["listing rules (LR)","上市规则"],
["prospectus regulation","招股说明书条例"],
["sponsor","保荐人"],
["takeover code","收购守则"],
["put up or shut up (PUSU)","要么报价要么闭嘴","收购守则第 2.6 条规则"],
["MiFID II","金融工具市场指令二"],
["best execution","最佳执行"],
["client categorisation","客户分类","零售 / 专业 / 合格对手方"],
["appropriateness / suitability","适当性 / 适合性"],
["product governance","产品治理","目标市场与分销策略"],
["inducements","利益诱导","禁止第三方收受非透明报酬"],
["costs and charges disclosure","成本与费用披露"],
["EMIR","欧洲市场基础设施条例"],
["clearing obligation","强制清算义务"],
["trade repository","交易存管库"],
["SFTR","证券融资交易条例"],
["settlement discipline","结算纪律"],
["buy-side / sell-side","买方 / 卖方"]
]);

VOCAB_DOMAINS[3].deck = VOCAB_DOMAINS[3].deck.concat([
["UK GDPR","英国通用数据保护条例"],
["Data Protection Act 2018","英国 2018 年数据保护法"],
["controller","控制者","决定处理目的与方式的主体"],
["processor","处理者","受控制者委托处理数据的主体"],
["joint controllers","共同控制者"],
["sub-processor","次级处理者"],
["data subject","数据主体"],
["personal data","个人数据"],
["special category data","特殊类别数据","种族、健康、性取向等，处理门槛更高"],
["criminal offence data","刑事犯罪数据","英国法下单独一类受保护数据"],
["lawful basis","合法性基础","六种，缺一不可处理"],
["consent","同意","须自由给出、具体、知情、明确"],
["legitimate interests","正当利益","需通过三步平衡测试 LIA"],
["vital interests","重大利益"],
["public task","公共任务"],
["data minimisation","数据最小化"],
["purpose limitation","目的限制"],
["storage limitation","存储限制"],
["accuracy principle","准确性原则"],
["accountability","问责原则","须能证明合规，而非仅仅声称"],
["data protection by design and default","默认与设计即合规"],
["privacy impact assessment (DPIA)","隐私影响评估"],
["records of processing activities (ROPA)","处理活动记录"],
["privacy notice","隐私声明"],
["transparency requirement","透明性要求"],
["data subject access request (DSAR)","数据主体访问请求","与可疑活动报告同缩写，须靠上下文区分"],
["one-month deadline","一个月答复期限","可延长两个月，须说明理由"],
["rectification","更正权"],
["right to erasure","删除权","亦称被遗忘权"],
["right to restriction","限制处理权"],
["right to data portability","数据可携带权"],
["right to object","反对权"],
["rights relating to automated decision-making","自动化决策相关权利","含画像 profiling"],
["solely automated decision","完全自动化决策"],
["human intervention","人工介入"],
["information notice / enforcement notice","信息通知 / 执法通知"],
["monetary penalty notice","罚款通知","英国上限为 1,750 万英镑或全球营业额 4%"],
["ICO","英国信息专员办公室","Information Commissioner's Office"],
["fee / registration","数据保护登记费"],
["international transfer","跨境传输"],
["adequacy regulations","充分性认定"],
["standard contractual clauses (SCCs)","标准合同条款"],
["International Data Transfer Agreement (IDTA)","国际数据传输协议","英国版替代 SCC 的独立工具"],
["UK Addendum","英国附录","在欧盟 SCC 上附加的英国增补条款"],
["transfer risk assessment (TRA)","传输风险评估"],
["data localisation","数据本地化"],
["government access","政府调取"],
["PECR","隐私与电子通信条例","管理 Cookie、邮件营销与来电营销"],
["cookie consent","Cookie 同意","须事先取得，不得默认勾选"],
["soft opt-in","软性同意","既有客户关系下可继续营销的前提条件"],
["direct marketing","直接营销"],
["personal data breach","个人数据泄露"],
["72-hour notification","72 小时通报","向 ICO 通报的时限"],
["data breach register","数据泄露台账"],
["anonymisation","匿名化","完全不可复原，脱离 GDPR 管辖"],
["pseudonymisation","假名化","可复原，仍属个人数据"],
["aggregated data","汇总数据"],
["retention schedule","保存期限表"],
["data mapping","数据映射"],
["data lineage","数据血缘"],
["records retention","档案留存"],
["subject rights request handling","数据主体权利请求处理"],
["data protection officer (DPO)","数据保护官"],
["employee monitoring","员工监控","涉及告知义务、比例原则与正当利益测试"],
["bring your own device (BYOD)","自带设备办公"],
["vendor due diligence","供应商尽职调查"],
["data processing agreement (DPA)","数据处理协议"]
]);

VOCAB_DOMAINS[5].deck = VOCAB_DOMAINS[5].deck.concat([
["Could you walk me through it?","你能带我过一遍吗？","请人逐步骤讲解，比 explain 更自然"],
["Can I just clarify one thing?","我想确认一点","会议中插话的礼貌切口"],
["Just to make sure I've got this right…","我想确认我理解无误……","校验理解的万能开场"],
["To build on what you said…","接着你刚才说的……","承接他人观点"],
["I see it slightly differently.","我的看法稍有不同","温和反对的标准句"],
["I'd push back on that.","这一点我可能有异议","比 I disagree 更职场"],
["That's a fair point, but…","说得有道理，不过……","先认可再反驳"],
["Where I'd land is…","我的结论会落在……","表达最终立场"],
["My inclination would be to…","我倾向于……","谨慎表达偏好"],
["On balance, I think…","权衡下来我认为……"],
["I'd err on the side of caution.","我会倾向于谨慎行事","合规岗位的高频表态"],
["It's a matter of judgement.","这属于判断范畴","承认无法给出唯一答案"],
["That sits outside my remit.","这不在我的职责范围内"],
["Let me take that away.","我回去查一下","不当场给答案的得体说法"],
["I'll revert to you.","我回头答复你","英式商务高频，不是「恢复」的意思"],
["Noted, with thanks.","收到，谢谢","便于留下书面记录"],
["For the avoidance of doubt…","为避免歧义……","法律文书与会议纪要常用"],
["Without prejudice to…","在不影响……的前提下"],
["to flag something","提示一个问题"],
["to loop someone in","把某人拉进沟通"],
["to take something offline","私下另行讨论","会议中搁置话题"],
["to park something","暂时搁置"],
["to circle back","稍后再谈"],
["to bottom out an issue","把问题彻底弄清楚"],
["to socialise a proposal","先小范围非正式征询意见"],
["to land a point","把观点讲清楚并被接受"],
["to push back the deadline","推迟截止日期"],
["to bite the bullet","硬着头皮做"],
["to get the ball rolling","开始启动"],
["to touch base","简短联络一下"],
["to be across something","对某事已掌握情况","英式用法，不是「跨越」"],
["to be on the front foot","主动出击"],
["heads-up","事先知会"],
["join the dots","把点连成线（把线索串起来）"],
["gap analysis","差距分析"],
["the ask","要求、诉求","口语化的名词用法"],
["bandwidth","精力余量","不是带宽，指能不能承接"],
["moving parts","变动因素"],
["join the call","接入会议"],
["dial-in details","电话会议拨入信息"],
["on mute","已静音"],
["you're breaking up","你那边声音断续"],
["apologies for the background noise","抱歉背景有噪音"],
["let's run through the agenda","我们过一遍议程"],
["any other business (AOB)","其他事项"],
["action points","待办事项"],
["matters arising","上次会议遗留事项"],
["meeting minutes","会议纪要"],
["paper","议案文件","会议文件统称"],
["committee paper","委员会议案"],
["executive summary","执行摘要"],
["recommendation","建议事项"],
["decision required","需决事项"],
["for information only","仅供知悉"],
["for discussion","供讨论"],
["for approval","待批准"],
["for noting","备查"],
["next steps","后续安排"],
["key takeaway","核心要点"],
["draft for comment","征求意见稿"],
["version control","版本管理"],
["stakeholder","利益相关方"],
["workstream","工作流"],
["deep dive","深入分析"],
["spot check","抽查"],
["proof of concept (POC)","概念验证"],
["pain point","痛点"],
["quick win","速赢项"],
["critical path","关键路径"],
["resource constraint","资源约束"],
["dependency","依赖项"],
["escalation","上报升级"],
["decision log","决策记录"]
]);
