/* 深化：合同与法律英语 / 财务会计与报表 / 贸易融资 / 数字资产与金融科技合规 */
VOCAB_DOMAINS[8].deck = VOCAB_DOMAINS[8].deck.concat([
["recital","鉴于条款","合同开头的背景陈述"],
["whereas","鉴于","陈述背景的事实性连接词"],
["operative provisions","正文条款","合同的实质权利义务部分"],
["boilerplate","标准条款 / 套话条款","末尾的通用条款统称"],
["proviso","但书","附带限制条件的条款"],
["notwithstanding","尽管有……的规定","法律英语中最强势的优先表达"],
["subject to","以……为条件","不能简单理解为「关于」"],
["without prejudice","不损害权利","既用于保留法律立场，也用于和解谈判"],
["severability","可分割性","某条无效不影响其余条款"],
["entire agreement clause","完整协议条款","排除此前一切口头与书面洽谈"],
["counterparts","副本","分签后共同构成同一份合同"],
["representations and warranties","陈述与保证","陈述针对事实，保证是合同承诺，违约救济不同"],
["covenant","承诺条款"],
["undertaking","承诺事项"],
["condition precedent","先决条件","满足后方才生效或放款"],
["condition subsequent","后决条件"],
["best endeavours","尽力义务","英国法下强度高于 reasonable endeavours"],
["reasonable endeavours","合理努力义务","低于 best，高于 commercially reasonable"],
["commercially reasonable endeavours","商业上合理的努力"],
["good faith","诚信"],
["material adverse change (MAC)","重大不利变化","并购与融资文件中的关键退出阀"],
["time is of the essence","时间为合同要素","逾期即构成根本违约"],
["indemnity","补偿条款","独立于违约救济的直接赔偿义务"],
["hold harmless","使免受损害"],
["cap on liability","责任上限"],
["exclusion of liability","责任排除"],
["consequential loss","间接损失","英国法下与 direct loss 的界线是判例争议焦点"],
["gross negligence","重大过失"],
["wilful misconduct","故意不当行为"],
["liquidated damages","约定违约金"],
["penalty clause","惩罚性条款","英国法下可能不可执行"],
["specific performance","强制履行"],
["injunctive relief","禁令救济"],
["interim / interlocutory injunction","临时禁令"],
["termination for cause","因违约终止"],
["termination for convenience","便利终止","须有权且通常需通知期"],
["survival clause","存续条款"],
["waiver","弃权","须书面且不得推定"],
["variation","变更","须由双方书面签署"],
["entire agreement","完整协议"],
["third party rights","第三方权利","英国 1999 年合同（第三方权利）法"],
["Contracts (Rights of Third Parties) Act 1999","合同（第三方权利）法 1999"],
["privity of contract","合同相对性"],
["deed","契据","无需对价即可执行，须符合签署形式"],
["consideration","对价","合同成立的核心要件"],
["execution","签署生效"],
["governing law","准据法"],
["jurisdiction clause","管辖条款"],
["expert determination","专家裁定","比仲裁更快更省的争议解决机制"],
["escalation clause","升级条款","先协商、再调解、后仲裁的阶梯安排"],
["LCIA / ICC arbitration","伦敦国际仲裁院 / 国际商会仲裁"],
["New York Convention","纽约公约","仲裁裁决跨国执行的依据"],
["restrictive covenant","限制性约款","竞业禁止、挖角禁止、保密义务"],
["non-compete / non-solicit / non-deal","竞业禁止 / 禁止招揽 / 禁止交易"],
["milestone payment","里程碑付款"],
["liquidated","已清算的 / 确定的"]
]);

VOCAB_DOMAINS[9].deck = VOCAB_DOMAINS[9].deck.concat([
["income statement","利润表"],
["statement of financial position","财务状况表","即资产负债表 balance sheet 的 IFRS 表述"],
["cash flow statement","现金流量表"],
["statement of changes in equity","所有者权益变动表"],
["notes to the financial statements","财务报表附注"],
["IFRS","国际财务报告准则"],
["UK GAAP / FRS 102","英国公认会计原则 / 财务报告准则 102"],
["IFRS 9","金融工具准则","引入预期信用损失模型"],
["expected credit loss (ECL)","预期信用损失","减值计提的三阶段模型"],
["stage 1 / 2 / 3 assets","减值三阶段资产","信用风险显著上升即进入第二阶段"],
["IFRS 15","收入准则"],
["IFRS 16","租赁准则","经营租赁入表，对银行客户财务分析影响巨大"],
["revenue recognition","收入确认"],
["accruals","应计项目"],
["prepayments","预付款项"],
["deferred income","递延收入"],
["provisions","预计负债"],
["contingent liability","或有负债"],
["off-balance sheet","表外"],
["goodwill","商誉"],
["intangible assets","无形资产"],
["tangible fixed assets","有形固定资产"],
["depreciation","折旧"],
["amortisation","摊销"],
["impairment test","减值测试"],
["recoverable amount","可收回金额"],
["value in use","使用价值"],
["discount rate / WACC","折现率 / 加权平均资本成本"],
["fair value hierarchy","公允价值层级","第一层报价、第二层可观察、第三层不可观察"],
["level 3 assets","第三层级资产","估值依赖模型假设，监管关注重点"],
["mark-to-market","按市值计价"],
["mark-to-model","按模型计价"],
["working capital","营运资金"],
["operating cash flow","经营现金流"],
["free cash flow","自由现金流"],
["EBITDA","息税折旧摊销前利润"],
["net interest margin","净息差"],
["cost-to-income ratio","成本收入比"],
["return on equity (ROE)","净资产收益率"],
["return on tangible equity (ROTE)","有形净资产收益率"],
["retained earnings","留存收益"],
["shareholders' equity","股东权益"],
["going concern","持续经营"],
["materiality","重要性","审计与会计的共同核心概念"],
["unqualified opinion","无保留意见","也就是「干净的」审计意见"],
["qualified opinion","保留意见"],
["adverse opinion","否定意见"],
["disclaimer of opinion","无法表示意见"],
["key audit matter","关键审计事项"],
["audit committee","审计委员会"],
["internal control over financial reporting","财务报告内部控制"],
["restatement","财务报表重述"],
["prior period adjustment","前期调整"],
["fraud risk in revenue recognition","收入确认舞弊风险","审计准则推定的固有风险"],
["journal entry testing","会计分录测试"],
["related party transaction","关联交易"],
["segment reporting","分部报告"],
["debt covenant","债务契约","财务指标触发即技术性违约"],
["covenant breach","违反债务契约"],
["waiver letter","豁免函"]
]);

VOCAB_DOMAINS[10].deck = VOCAB_DOMAINS[10].deck.concat([
["clean bill of lading","清洁提单","无货物不良批注"],
["shipped on board bill of lading","已装船提单"],
["order bill of lading","指示提单","可背书转让"],
["straight bill of lading","记名提单","不可转让"],
["sea waybill","海运单","非物权凭证，不可转让"],
["air waybill (AWB)","空运单"],
["multimodal transport document","多式联运单据"],
["freight forwarder","货运代理"],
["shipper / consignee / notify party","托运人 / 收货人 / 通知方"],
["commercial invoice","商业发票"],
["packing list","装箱单"],
["inspection certificate","检验证书"],
["insurance policy / certificate","保险单 / 保险凭证"],
["bill of exchange","汇票"],
["tenor","票据期限"],
["at sight / usance","即期 / 远期"],
["documents against payment (D/P)","付款交单","买方付款后才拿到单据"],
["documents against acceptance (D/A)","承兑交单","买方承兑即可拿单，风险显著更高"],
["documentary collection","跟单托收"],
["open account","赊销","卖方风险最大、成本最低"],
["advance payment","预付货款"],
["consignment","寄售"],
["standby letter of credit (SBLC)","备用信用证","实质是银行担保"],
["revolving letter of credit","循环信用证"],
["transferable letter of credit","可转让信用证"],
["back-to-back letter of credit","背对背信用证"],
["confirmed irrevocable L/C","保兑不可撤销信用证"],
["issuing bank / advising bank / confirming bank","开证行 / 通知行 / 保兑行"],
["negotiating bank","议付行"],
["discrepancy","不符点","单据与信用证条款不一致"],
["waiver of discrepancies","不符点豁免"],
["UCP 600","跟单信用证统一惯例 600"],
["ISBP","国际标准银行实务"],
["eUCP","电子交单附则"],
["Incoterms 2020","国际贸易术语解释通则 2020"],
["EXW / FOB / CIF / CIP / DAP / DDP","工厂交货 / 船上交货 / 成本保险费加运费 / 运费保险费付至 / 目的地交货 / 完税后交货"],
["on-demand guarantee","见索即付保函","独立保函，银行付款义务不与基础合同挂钩"],
["performance bond","履约保函"],
["advance payment guarantee","预付款保函"],
["demand guarantee","见索即付担保"],
["bank guarantee","银行保函"],
["factoring","保理","应收账款买断加管理"],
["forfaiting","福费廷","无追索权买断中长期票据"],
["invoice discounting","发票贴现","不通知买方的融资安排"],
["supply chain finance","供应链金融"],
["reverse factoring","反向保理","买方主导，对供应商融资成本友好"],
["receivables purchase agreement","应收账款购买协议"],
["trade-based money laundering (TBML)","贸易洗钱"],
["over- and under-invoicing","高开 / 低开发票"],
["multiple invoicing","重复开票"],
["falsely described goods","货物描述不实"],
["carousel transaction","循环交易"],
["red flag indicator","红旗指标"],
["wire stripping","电文剥除","篡改汇款报文隐藏付款方信息"],
["trade finance risk participation","贸易融资风险参与"],
["commodity finance","大宗商品融资"],
["borrowing base","借款基数"],
["pre-export finance","出口前融资"]
]);

VOCAB_DOMAINS[11].deck = VOCAB_DOMAINS[11].deck.concat([
["virtual asset service provider (VASP)","虚拟资产服务提供者","FATF 定义的受监管主体"],
["cryptoasset business","加密资产业务","英国 FCA 的注册类别"],
["fiat-backed stablecoin","法币背书稳定币","英国 2023 年后纳入支付监管"],
["e-money token","电子货币代币"],
["central bank digital currency (CBDC)","央行数字货币","英国称为 digital pound"],
["custodial wallet","托管钱包","服务商持有私钥，构成资产保管义务"],
["non-custodial wallet","非托管钱包"],
["private key","私钥"],
["hot / cold wallet","热钱包 / 冷钱包"],
["centralised exchange (CEX)","中心化交易所"],
["decentralised exchange (DEX)","去中心化交易所"],
["DeFi","去中心化金融"],
["smart contract","智能合约"],
["non-fungible token (NFT)","非同质化代币"],
["tokenisation","代币化"],
["security token","证券型代币"],
["utility token","功能型代币"],
["MiCA","欧盟加密资产市场监管条例"],
["travel rule","旅行规则","FATF 第 16 号建议，转账须附带发起方与受益方信息"],
["originator / beneficiary information","发起方 / 受益方信息"],
["unhosted wallet","自托管钱包","转账时的额外尽调触发点"],
["on-chain analytics","链上分析"],
["blockchain forensics","区块链取证"],
["chain-hopping","跨链跳转","通过多链转换混淆资金来源"],
["mixer / tumbler","混币器","隐私增强服务，受制裁关注"],
["privacy coin","隐私币"],
["distributed ledger technology (DLT)","分布式账本技术"],
["consensus mechanism","共识机制"],
["proof of work / proof of stake","工作量证明 / 权益证明"],
["staking / validator","质押 / 验证节点"],
["cross-chain bridge","跨链桥","黑客攻击高发环节"],
["rug pull","拉地毯跑路","项目方抽走流动性的退出骗局"],
["initial coin offering (ICO)","首次代币发行"],
["crypto travel rule compliance","加密旅行规则合规"],
["open banking","开放银行","英国是这一制度的发源地，由 CMA 强制推行"],
["PSD2","第二版支付服务指令"],
["strong customer authentication (SCA)","强客户认证"],
["embedded finance","嵌入式金融"],
["buy now pay later (BNPL)","先买后付","英国已纳入 FCA 监管"],
["robo-advisory","智能投顾"],
["insurtech / regtech / suptech","保险科技 / 监管科技 / 监管科技（监管方侧）"],
["model risk management","模型风险管理"],
["model validation","模型验证"],
["model drift","模型漂移"],
["algorithmic bias","算法偏见"],
["explainability","可解释性"],
["AI Act","欧盟人工智能法案"],
["high-risk AI system","高风险人工智能系统"],
["cloud outsourcing","云外包","关键第三方与退出计划是监管重点"],
["critical third party (CTP)","关键第三方","FSMA 2023 新增的直接监管对象"],
["exit plan","退出计划","防范供应商锁定"],
["concentration risk","集中度风险"]
]);
