/* 新增领域：金融犯罪、欺诈与执法（crime） */
VOCAB_DOMAINS[14].deck = [
["financial crime","金融犯罪","银行业合规的核心业务线，含洗钱、欺诈、制裁、贿赂"],
["economic crime","经济犯罪","英国《2023 年经济犯罪与企业透明法》的法定用语"],
["fraud","欺诈"],
["bribery and corruption","贿赂与腐败"],
["tax evasion","逃税","刑事犯罪；与 tax avoidance 有本质区别"],
["tax avoidance","避税","合法但可能被认定为 aggressive"],
["facilitation of tax evasion","协助逃税","英国 2017 年刑事财政法创设的企业犯罪"],
["failure to prevent","未能预防","英国法下企业犯罪的典型归责模式"],
["failure to prevent bribery","未能预防贿赂","2010 年反贿赂法第六条"],
["failure to prevent fraud","未能预防欺诈","2023 年经济犯罪法新增罪名"],
["adequate procedures","充分程序","反贿赂法的唯一抗辩事由"],
["POCA 2002","2002 年犯罪所得法","英国反洗钱刑事体系的根基"],
["SOCPA 2005","2005 年严重有组织犯罪与警察法"],
["suspicion","怀疑","英国法下无需确证，标准极低且主观"],
["reasonable grounds to suspect","有合理理由怀疑"],
["knowledge","明知"],
["criminal conduct","犯罪行为"],
["benefit from criminal conduct","从犯罪行为中获益"],
["civil recovery","民事追缴","无需刑事定罪即可追回资产"],
["unexplained wealth order (UWO)","财富来源不明令","针对高价值资产的强调查权"],
["account freezing order (AFO)","账户冻结令"],
["account forfeiture order","账户没收令"],
["restraint order","限制令","刑事程序中冻结被告资产"],
["confiscation order","没收令"],
["cash seizure","现金扣押"],
["proceeds of crime","犯罪所得"],
["asset recovery","资产追回"],
["Serious Fraud Office (SFO)","英国严重欺诈办公室"],
["CPS","英国皇家检察署","Crown Prosecution Service"],
["Financial Conduct Authority (FCA)","英国金融行为监管局"],
["Prudential Regulation Authority (PRA)","英国审慎监管局"],
["deferred prosecution agreement (DPA)","暂缓起诉协议","企业缴纳罚款并整改以换取不起诉"],
["corporate criminal offence","企业犯罪"],
["identification principle","同一性原则","英国法下须证明「指挥意志」有责"],
["senior management liability","高级管理层责任"],
["consent order","同意令"],
["proceeds of Crime Act investigation","犯罪所得法调查"],
["mutual legal assistance (MLA)","司法互助"],
["letters rogatory","司法委托书"],
["freezing injunction (Mareva)","玛瑞瓦禁令","全球资产冻结令"],
["Norwich Pharmacal order","诺里奇药厂令","强制第三方披露信息的命令"],
["section 2 notice","第 2 条通知","SFO 的强制取证权"],
["search warrant","搜查令"],
["dawn raid","突击搜查","监管或执法机构上门"],
["compelled interview","强制询问"],
["privilege against self-incrimination","不得自证其罪特权"],
["legal professional privilege (LPP)","法律职业特权"],
["litigation privilege","诉讼特权"],
["advice privilege","法律意见特权"],
["Upjohn warning","厄普约翰警示","公司律师访谈员工前须声明代理的是公司而非员工"],
["conflict of interest","利益冲突"],
["insider threat","内部威胁"],
["whistleblowing","举报","英国受 1998 年公共利益披露法保护"],
["protected disclosure","受保护的披露"],
["detriment","不利对待","举报人受保护的核心禁止行为"],
["speak-up channel","举报渠道"],
["external reporting hotline","外部举报热线"],
["internal investigation","内部调查"],
["forensic investigation","取证调查"],
["e-discovery","电子取证"],
["preservation notice","证据保全通知"],
["legal hold","法律留置","禁止删除相关文件"],
["data sampling","数据抽样"],
["interview under caution","具警示讯问"],
["disciplinary process","纪律程序"],
["gross misconduct","严重不当行为"],
["summary dismissal","即时解雇"],
["regulatory referral","监管移送"],
["enforcement action","执法行动"],
["settlement agreement","和解协议"],
["disgorgement","吐出违法所得"],
["remediation plan","整改计划"],
["lessons learned review","教训总结复盘"]
];

/* 新增领域：金融产品与市场工具（prod） */
VOCAB_DOMAINS[15].deck = [
["equity","股票 / 权益"],
["ordinary share","普通股"],
["preference share","优先股"],
["bond / fixed income","债券 / 固定收益"],
["government bond / gilt","政府债券 / 英国金边债券"],
["corporate bond","公司债"],
["high-yield bond","高收益债","俗称垃圾债"],
["investment grade","投资级"],
["subordinated debt","次级债"],
["convertible bond","可转换债券"],
["covered bond","担保债券"],
["callable / puttable bond","可赎回 / 可回售债券"],
["coupon / yield / duration","票息 / 收益率 / 久期"],
["credit spread","信用利差"],
["rating agency / credit rating","评级机构 / 信用评级"],
["investment bank","投资银行"],
["corporate finance","公司金融 / 投行业务"],
["M&A advisory","并购顾问"],
["leveraged buyout (LBO)","杠杆收购"],
["private equity","私募股权"],
["venture capital","风险投资"],
["IPO / secondary offering","首次公开发行 / 增发"],
["rights issue","供股"],
["bookbuilding","簿记建档"],
["roadshow","路演"],
["due diligence (DD)","尽职调查","注意：此处指交易尽调，与客户尽调 CDD 不同"],
["data room","数据库房","交易尽调的资料库"],
["term sheet","条款清单","交易核心商业条款的摘要"],
["SPA / SHA","股权购买协议 / 股东协议"],
["disclosure letter","披露函","对保证条款的例外披露，界定索赔边界"],
["escrow","托管 / 第三方保管"],
["earn-out","业绩对赌"],
["completion / closing","交割"],
["fund","基金"],
["UCITS","可转让证券集合投资计划"],
["AIFMD","另类投资基金管理人指令"],
["open-ended / closed-ended fund","开放式 / 封闭式基金"],
["ETF","交易所交易基金"],
["NAV","资产净值","Net Asset Value"],
["management fee / performance fee","管理费 / 业绩报酬"],
["side letter","附属函","对特定投资者的特别约定"],
["prime broker","主经纪商"],
["fund administrator","基金行政管理人"],
["depositary","托管人（基金）"],
["mandate","委托 / 授权","客户给出的投资授权范围"],
["discretionary management","全权委托管理"],
["advisory mandate","投资顾问型授权"],
["benchmark / index","基准 / 指数"],
["tracking error","跟踪误差"],
["asset allocation","资产配置"],
["portfolio rebalancing","组合再平衡"],
["hedging","对冲"],
["long / short position","多头 / 空头头寸"],
["short selling","卖空","英国受 EU 236/2012 及本土规则约束"],
["margin / leverage","保证金 / 杠杆"],
["securities financing transaction","证券融资交易"],
["sukuk","伊斯兰债券"],
["structured product","结构性产品","零售分销适格性是监管关注重点"],
["derivative types","衍生品类型","远期、期货、期权、互换共四大类"],
["option / call / put","期权 / 看涨 / 看跌"],
["futures contract","期货合约"],
["credit default swap (CDS)","信用违约互换"],
["collateralised debt obligation (CDO)","债务担保证券"],
["central counterparty (CCP)","中央对手方"],
["cleared / uncleared margin","已清算 / 未清算保证金"],
["suitability assessment","适合性评估"],
["target market determination","目标市场认定"]
];
