/* 新增领域：风险管理与内部控制（risk） */
VOCAB_DOMAINS[16].deck = [
["three lines of defence","三道防线","业务一线 / 风险合规二线 / 内审三线"],
["first line of defence","第一道防线","业务部门自担风险责任"],
["second line of defence","第二道防线","风险与合规的监督与挑战职能"],
["third line of defence","第三道防线","内部审计的独立确认"],
["enterprise risk management (ERM)","全面风险管理"],
["risk taxonomy","风险分类体系"],
["risk appetite statement (RAS)","风险偏好声明"],
["risk tolerance / risk limit","风险容忍度 / 风险限额"],
["risk register","风险登记册"],
["key risk indicator (KRI)","关键风险指标","先行指标，用于预警"],
["key performance indicator (KPI)","关键绩效指标"],
["risk owner","风险责任人"],
["inherent risk","固有风险","控制前风险"],
["residual risk","剩余风险","控制后风险"],
["control environment","控制环境"],
["control design effectiveness","控制设计有效性"],
["control operating effectiveness","控制运行有效性"],
["design deficiency","设计缺陷"],
["operating deficiency","运行缺陷"],
["key control","关键控制"],
["compensating control","补偿性控制"],
["preventive / detective control","预防性 / 检查性控制"],
["manual / automated control","手工 / 自动化控制"],
["segregation of duties","职责分离"],
["maker-checker","经办复核制","英国金融机构的基础控制要求"],
["four-eyes principle","四眼原则"],
["authorisation limit","授权权限"],
["delegated authority","授权"],
["control testing","控制测试"],
["walkthrough test","穿行测试","从交易起点走到终点验证控制链路"],
["sample size","样本量"],
["exception report","例外报告"],
["root cause analysis","根因分析"],
["issue management","问题管理"],
["self-assessment","自评估"],
["control self-assessment (CSA)","控制自评估"],
["risk and control self-assessment (RCSA)","风险与控制自评估"],
["management information (MI)","管理信息 / 管理报表"],
["risk committee","风险委员会"],
["board risk appetite","董事会风险偏好"],
["operational risk","操作风险"],
["conduct risk","行为风险","以客户结果和员工行为为核心的独立风险类别"],
["compliance risk","合规风险"],
["reputational risk","声誉风险"],
["strategic risk","战略风险"],
["credit risk","信用风险"],
["market risk","市场风险"],
["liquidity risk","流动性风险"],
["model risk","模型风险"],
["information security risk","信息安全风险"],
["third-party risk","第三方风险"],
["concentration risk","集中度风险"],
["risk culture","风险文化","监管越来越关注「软性」维度"],
["tone from the top","高层基调"],
["speak-up culture","敢于发声的文化"],
["near miss","未遂事件"],
["loss event / incident","损失事件 / 事件"],
["risk-adjusted return","风险调整后收益"],
["stress and scenario testing","压力与情景测试"],
["reverse stress testing","反向压力测试","先假设业务不可持续，再倒推触发条件"],
["heat map","风险热力图"],
["material risk taker","重大风险承担者"],
["risk-weighted exposure","风险加权敞口"]
];

/* 新增领域：ESG 与可持续金融合规（esg） */
VOCAB_DOMAINS[17].deck = [
["ESG","环境、社会与治理"],
["sustainable finance","可持续金融"],
["climate-related financial risk","气候相关金融风险"],
["physical risk / transition risk","物理风险 / 转型风险"],
["TCFD","气候相关财务信息披露工作组"],
["climate risk disclosure","气候风险披露","英国已对大型公司强制要求"],
["scope 1 / 2 / 3 emissions","范围一 / 二 / 三排放","范围三即供应链与融资排放"],
["financed emissions","融资排放","银行投向客户产生的碳排放"],
["net zero commitment","净零承诺"],
["carbon footprint","碳足迹"],
["transition plan","转型计划"],
["decarbonisation pathway","脱碳路径"],
["greenwashing","漂绿","夸大可持续表现的误导性陈述，已成执法重点"],
["greenhushing","绿色沉默","因怕被指漂绿而选择不披露"],
["misleading sustainability claim","误导性可持续陈述"],
["sustainability-linked loan (SLL)","可持续发展挂钩贷款"],
["green bond","绿色债券"],
["sustainability-linked bond","可持续发展挂钩债券"],
["green loan principles","绿色贷款原则"],
["use of proceeds","募集资金用途"],
["second party opinion","第二方意见"],
["SFDR","可持续金融披露条例"],
["EU Taxonomy","欧盟可持续经济活动分类"],
["UK Green Taxonomy","英国绿色分类目录"],
["principal adverse impact","主要不利影响"],
["ESG rating provider","ESG 评级机构","英国已就其透明度与治理开展监管咨询"],
["stewardship","尽责管理","机构投资者对被投企业的监督义务"],
["engagement / escalation","参与沟通 / 升级行动"],
["voting policy","投票政策"],
["just transition","公正转型","兼顾低碳转型对就业与社区的影响"],
["social risk","社会风险"],
["human rights due diligence","人权尽职调查"],
["modern slavery","现代奴役","英国《2015 年现代奴役法》要求大企业发布报告"],
["supply chain due diligence","供应链尽职调查"],
["biodiversity risk","生物多样性风险"],
["nature-related disclosures (TNFD)","自然相关财务信息披露"],
["diversity and inclusion (D&I)","多元与包容"],
["gender pay gap reporting","性别薪酬差距报告"],
["board diversity target","董事会多元目标"],
["governance standards","治理标准"],
["double materiality","双重重要性","既看财务影响，也看对外部的影响"],
["climate scenario analysis","气候情景分析"],
["stranded asset","搁浅资产"],
["carbon border adjustment mechanism (CBAM)","碳边境调节机制"],
["emissions trading scheme","碳排放交易体系"]
];
